--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_1
local Image_1 = ccui.Layout:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:setClippingEnabled(false)
Image_1:setBackGroundColorOpacity(102)
Image_1:setTouchEnabled(true);
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(286)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setAnchorPoint(0.5000, 0.5000)
Image_1:setPosition(-125.0000, -0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setSize({width = 159.0000, height = 51.0000})
layout:setLeftMargin(-204.5000)
layout:setRightMargin(45.5000)
layout:setTopMargin(-25.0000)
layout:setBottomMargin(-26.0000)
Node:addChild(Image_1)

--Create img_bj
local img_bj = ccui.ImageView:create()
img_bj:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_bj:loadTexture("hall/common/new_btn_noangle.png",1)
img_bj:setScale9Enabled(true)
img_bj:setCapInsets({x = 5, y = 5, width = 1, height = 1})
img_bj:setLayoutComponentEnabled(true)
img_bj:setName("img_bj")
img_bj:setTag(287)
img_bj:setCascadeColorEnabled(true)
img_bj:setCascadeOpacityEnabled(true)
img_bj:setPosition(79.5000, 25.1736)
img_bj:setColor({r = 78, g = 148, b = 229})
layout = ccui.LayoutComponent:bindLayoutComponent(img_bj)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4936)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 159.0000, height = 51.0000})
layout:setTopMargin(0.3264)
layout:setBottomMargin(-0.3264)
Image_1:addChild(img_bj)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("")
Text_1:setFontSize(29)
Text_1:setString([[报名费:]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(45)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(79.5000, 25.5000)
Text_1:setTextColor({r = 254, g = 254, b = 254})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6415)
layout:setPercentHeight(0.5686)
layout:setSize({width = 102.0000, height = 29.0000})
layout:setLeftMargin(28.5000)
layout:setRightMargin(28.5000)
layout:setTopMargin(11.0000)
layout:setBottomMargin(11.0000)
Image_1:addChild(Text_1)

--Create img_ej
local img_ej = ccui.ImageView:create()
img_ej:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/room.plist")
img_ej:loadTexture("hall/room/match/img_kuan1.png",1)
img_ej:setScale9Enabled(true)
img_ej:setCapInsets({x = 7, y = 8, width = 5, height = 5})
img_ej:setTouchEnabled(true);
img_ej:setLayoutComponentEnabled(true)
img_ej:setName("img_ej")
img_ej:setTag(50)
img_ej:setCascadeColorEnabled(true)
img_ej:setCascadeOpacityEnabled(true)
img_ej:setVisible(false)
img_ej:setPosition(80.9800, 53.9229)
layout = ccui.LayoutComponent:bindLayoutComponent(img_ej)
layout:setSize({width = 255.0000, height = 52.0000})
layout:setLeftMargin(-46.5200)
layout:setRightMargin(-208.4800)
layout:setTopMargin(-79.9229)
layout:setBottomMargin(27.9229)
Node:addChild(img_ej)

--Create txt_num
local txt_num = ccui.Text:create()
txt_num:ignoreContentAdaptWithSize(true)
txt_num:setTextAreaSize({width = 0, height = 0})
txt_num:setFontSize(24)
txt_num:setString([[10]])
txt_num:setLayoutComponentEnabled(true)
txt_num:setName("txt_num")
txt_num:setTag(52)
txt_num:setCascadeColorEnabled(true)
txt_num:setCascadeOpacityEnabled(true)
txt_num:setAnchorPoint(0.0000, 0.5000)
txt_num:setPosition(87.8400, 22.3600)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_num)
layout:setPositionPercentX(0.3445)
layout:setPositionPercentY(0.4300)
layout:setPercentWidth(0.1020)
layout:setPercentHeight(0.5385)
layout:setSize({width = 26.0000, height = 28.0000})
layout:setLeftMargin(87.8400)
layout:setRightMargin(141.1600)
layout:setTopMargin(15.6400)
layout:setBottomMargin(8.3600)
img_ej:addChild(txt_num)

--Create img_gignup_sl_icon
local img_gignup_sl_icon = ccui.ImageView:create()
img_gignup_sl_icon:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/room.plist")
img_gignup_sl_icon:loadTexture("hall/room/match/icon/item_s_wxhb.png",1)
img_gignup_sl_icon:setLayoutComponentEnabled(true)
img_gignup_sl_icon:setName("img_gignup_sl_icon")
img_gignup_sl_icon:setTag(51)
img_gignup_sl_icon:setCascadeColorEnabled(true)
img_gignup_sl_icon:setCascadeOpacityEnabled(true)
img_gignup_sl_icon:setPosition(54.8025, 25.3623)
layout = ccui.LayoutComponent:bindLayoutComponent(img_gignup_sl_icon)
layout:setPositionPercentX(0.2149)
layout:setPositionPercentY(0.4877)
layout:setPercentWidth(0.1961)
layout:setPercentHeight(0.9615)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(29.8025)
layout:setRightMargin(175.1975)
layout:setTopMargin(1.6377)
layout:setBottomMargin(0.3623)
img_ej:addChild(img_gignup_sl_icon)

--Create img_fun
local img_fun = ccui.Layout:create()
img_fun:ignoreContentAdaptWithSize(false)
img_fun:setClippingEnabled(false)
img_fun:setBackGroundColorOpacity(102)
img_fun:setTouchEnabled(true);
img_fun:setLayoutComponentEnabled(true)
img_fun:setName("img_fun")
img_fun:setTag(288)
img_fun:setCascadeColorEnabled(true)
img_fun:setCascadeOpacityEnabled(true)
img_fun:setAnchorPoint(0.5000, 0.5000)
img_fun:setPosition(82.0000, -0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_fun)
layout:setSize({width = 255.0000, height = 51.0000})
layout:setLeftMargin(-45.5000)
layout:setRightMargin(-209.5000)
layout:setTopMargin(-24.7000)
layout:setBottomMargin(-26.3000)
Node:addChild(img_fun)

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_bg:loadTexture("hall/common/new_btn_noangle.png",1)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 5, y = 4, width = 1, height = 1})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(289)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setPosition(127.5000, 25.5000)
img_bg:setColor({r = 219, g = 233, b = 248})
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 255.0000, height = 51.0000})
img_fun:addChild(img_bg)

--Create txt_num
local txt_num = ccui.Text:create()
txt_num:ignoreContentAdaptWithSize(true)
txt_num:setTextAreaSize({width = 0, height = 0})
txt_num:setFontName("")
txt_num:setFontSize(32)
txt_num:setString([[2000]])
txt_num:setLayoutComponentEnabled(true)
txt_num:setName("txt_num")
txt_num:setTag(49)
txt_num:setCascadeColorEnabled(true)
txt_num:setCascadeOpacityEnabled(true)
txt_num:setAnchorPoint(0.0000, 0.5000)
txt_num:setPosition(88.2000, 25.5000)
txt_num:setTextColor({r = 255, g = 153, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_num)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3459)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2510)
layout:setPercentHeight(0.6471)
layout:setSize({width = 64.0000, height = 33.0000})
layout:setLeftMargin(88.2000)
layout:setRightMargin(102.8000)
layout:setTopMargin(9.0000)
layout:setBottomMargin(9.0000)
img_fun:addChild(txt_num)

--Create img_gignup_cu_icon
local img_gignup_cu_icon = ccui.ImageView:create()
img_gignup_cu_icon:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/room.plist")
img_gignup_cu_icon:loadTexture("hall/room/match/icon/item_s_jd.png",1)
img_gignup_cu_icon:setLayoutComponentEnabled(true)
img_gignup_cu_icon:setName("img_gignup_cu_icon")
img_gignup_cu_icon:setTag(48)
img_gignup_cu_icon:setCascadeColorEnabled(true)
img_gignup_cu_icon:setCascadeOpacityEnabled(true)
img_gignup_cu_icon:setPosition(53.5500, 25.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_gignup_cu_icon)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2100)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1961)
layout:setPercentHeight(0.9804)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(28.5500)
layout:setRightMargin(176.4500)
layout:setTopMargin(0.5000)
layout:setBottomMargin(0.5000)
img_fun:addChild(img_gignup_cu_icon)

--Create img_jt
local img_jt = ccui.ImageView:create()
img_jt:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/room.plist")
img_jt:loadTexture("hall/room/match/btn_sjt.png",1)
img_jt:setLayoutComponentEnabled(true)
img_jt:setName("img_jt")
img_jt:setTag(47)
img_jt:setCascadeColorEnabled(true)
img_jt:setCascadeOpacityEnabled(true)
img_jt:setPosition(213.9760, 24.8900)
img_jt:setRotationSkewX(180.0000)
img_jt:setRotationSkewY(180.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_jt)
layout:setPositionPercentX(0.8391)
layout:setPositionPercentY(0.4880)
layout:setPercentWidth(0.1255)
layout:setPercentHeight(0.3333)
layout:setSize({width = 32.0000, height = 17.0000})
layout:setLeftMargin(197.9760)
layout:setRightMargin(25.0240)
layout:setTopMargin(17.6100)
layout:setBottomMargin(16.3900)
img_fun:addChild(img_jt)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

