--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create goodbtn
local goodbtn = ccui.Layout:create()
goodbtn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/store.plist")
goodbtn:setBackGroundImage("hall/store/Bottomframe_1.jpg",1)
goodbtn:setClippingEnabled(false)
goodbtn:setBackGroundImageCapInsets({x = 4, y = 2, width = 263, height = 194})
goodbtn:setBackGroundColorOpacity(102)
goodbtn:setBackGroundImageScale9Enabled(true)
goodbtn:setTouchEnabled(true);
goodbtn:setLayoutComponentEnabled(true)
goodbtn:setName("goodbtn")
goodbtn:setTag(152)
goodbtn:setCascadeColorEnabled(true)
goodbtn:setCascadeOpacityEnabled(true)
goodbtn:setAnchorPoint(0.5000, 0.5000)
goodbtn:setPosition(135.5000, -125.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(goodbtn)
layout:setSize({width = 271.0000, height = 250.0000})
layout:setRightMargin(-271.0000)
layout:setBottomMargin(-250.0000)
Node:addChild(goodbtn)

--Create nametext_good
local nametext_good = ccui.Text:create()
nametext_good:ignoreContentAdaptWithSize(true)
nametext_good:setTextAreaSize({width = 0, height = 0})
nametext_good:setFontName("")
nametext_good:setFontSize(28)
nametext_good:setString([[Text Label]])
nametext_good:setTextHorizontalAlignment(1)
nametext_good:setTextVerticalAlignment(1)
nametext_good:setLayoutComponentEnabled(true)
nametext_good:setName("nametext_good")
nametext_good:setTag(154)
nametext_good:setCascadeColorEnabled(true)
nametext_good:setCascadeOpacityEnabled(true)
nametext_good:setAnchorPoint(0.0000, 0.5000)
nametext_good:setPosition(11.0000, 221.0000)
nametext_good:setTextColor({r = 51, g = 51, b = 51})
layout = ccui.LayoutComponent:bindLayoutComponent(nametext_good)
layout:setPositionPercentX(0.0406)
layout:setPositionPercentY(0.8840)
layout:setPercentWidth(0.5166)
layout:setPercentHeight(0.1120)
layout:setSize({width = 140.0000, height = 28.0000})
layout:setLeftMargin(11.0000)
layout:setRightMargin(120.0000)
layout:setTopMargin(15.0000)
layout:setBottomMargin(207.0000)
goodbtn:addChild(nametext_good)

--Create img_good
local img_good = ccui.ImageView:create()
img_good:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/giftNodeVeiw.plist")
img_good:loadTexture("hall/gift/img_loading.png",1)
img_good:setLayoutComponentEnabled(true)
img_good:setName("img_good")
img_good:setTag(155)
img_good:setCascadeColorEnabled(true)
img_good:setCascadeOpacityEnabled(true)
img_good:setPosition(135.5000, 123.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_good)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4920)
layout:setPercentWidth(0.4502)
layout:setPercentHeight(0.4880)
layout:setSize({width = 122.0000, height = 122.0000})
layout:setLeftMargin(74.5000)
layout:setRightMargin(74.5000)
layout:setTopMargin(66.0000)
layout:setBottomMargin(62.0000)
goodbtn:addChild(img_good)

--Create img
local img = ccui.ImageView:create()
img:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/giftNodeVeiw.plist")
img:loadTexture("hall/gift/img_loading.png",1)
img:setLayoutComponentEnabled(true)
img:setName("img")
img:setTag(156)
img:setCascadeColorEnabled(true)
img:setCascadeOpacityEnabled(true)
img:setPosition(56.0000, 23.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img)
layout:setPositionPercentX(0.2066)
layout:setPositionPercentY(0.0920)
layout:setPercentWidth(0.1697)
layout:setPercentHeight(0.1840)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(33.0000)
layout:setRightMargin(192.0000)
layout:setTopMargin(204.0000)
goodbtn:addChild(img)

--Create pricetext_good
local pricetext_good = ccui.Text:create()
pricetext_good:ignoreContentAdaptWithSize(true)
pricetext_good:setTextAreaSize({width = 0, height = 0})
pricetext_good:setFontName("")
pricetext_good:setFontSize(34)
pricetext_good:setString([[x0]])
pricetext_good:setTextHorizontalAlignment(1)
pricetext_good:setTextVerticalAlignment(1)
pricetext_good:setLayoutComponentEnabled(true)
pricetext_good:setName("pricetext_good")
pricetext_good:setTag(157)
pricetext_good:setCascadeColorEnabled(true)
pricetext_good:setCascadeOpacityEnabled(true)
pricetext_good:setAnchorPoint(0.0000, 0.5000)
pricetext_good:setPosition(93.0000, 23.0000)
pricetext_good:setTextColor({r = 51, g = 51, b = 51})
layout = ccui.LayoutComponent:bindLayoutComponent(pricetext_good)
layout:setPositionPercentX(0.3432)
layout:setPositionPercentY(0.0920)
layout:setPercentWidth(0.1255)
layout:setPercentHeight(0.1360)
layout:setSize({width = 34.0000, height = 34.0000})
layout:setLeftMargin(93.0000)
layout:setRightMargin(144.0000)
layout:setTopMargin(210.0000)
layout:setBottomMargin(6.0000)
goodbtn:addChild(pricetext_good)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

