--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create container
local container = ccui.Layout:create()
container:ignoreContentAdaptWithSize(false)
container:setClippingEnabled(false)
container:setBackGroundColorOpacity(102)
container:setTouchEnabled(true);
container:setLayoutComponentEnabled(true)
container:setName("container")
container:setTag(119)
container:setCascadeColorEnabled(true)
container:setCascadeOpacityEnabled(true)
container:setPosition(142.0000, 43.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(container)
layout:setSize({width = 1096.0000, height = 634.0000})
layout:setLeftMargin(142.0000)
layout:setRightMargin(-1238.0000)
layout:setTopMargin(-677.0000)
layout:setBottomMargin(43.0000)
Node:addChild(container)

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_bg:loadTexture("hall/common/new_pop_bg.png",1)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 6, y = 69, width = 5, height = 2})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(979)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setAnchorPoint(0.0000, 0.0000)
img_bg:setPosition(276.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentX(0.2518)
layout:setPercentWidth(0.7445)
layout:setPercentHeight(1.0174)
layout:setSize({width = 816.0000, height = 645.0000})
layout:setLeftMargin(276.0000)
layout:setRightMargin(4.0000)
layout:setTopMargin(-11.0000)
container:addChild(img_bg)

--Create img_games
local img_games = ccui.ImageView:create()
img_games:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_games:loadTexture("hall/common/new_pop_right_bg.png",1)
img_games:setScale9Enabled(true)
img_games:setCapInsets({x = 4, y = 8, width = 3, height = 4})
img_games:setLayoutComponentEnabled(true)
img_games:setName("img_games")
img_games:setTag(799)
img_games:setCascadeColorEnabled(true)
img_games:setCascadeOpacityEnabled(true)
img_games:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_games)
layout:setPercentWidth(0.2550)
layout:setPercentHeight(1.0174)
layout:setSize({width = 279.5000, height = 645.0000})
layout:setRightMargin(816.5000)
layout:setTopMargin(-11.0000)
container:addChild(img_games)

--Create list_games
local list_games = ccui.ListView:create()
list_games:setItemsMargin(1)
list_games:setDirection(1)
list_games:setGravity(0)
list_games:ignoreContentAdaptWithSize(false)
list_games:setClippingEnabled(true)
list_games:setBackGroundImageCapInsets({x = -8, y = -8, width = 12, height = 16})
list_games:setBackGroundColorOpacity(102)
list_games:setBackGroundImageScale9Enabled(true)
list_games:setLayoutComponentEnabled(true)
list_games:setName("list_games")
list_games:setTag(124)
list_games:setCascadeColorEnabled(true)
list_games:setCascadeOpacityEnabled(true)
list_games:setPosition(0.0000, 6.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(list_games)
layout:setPositionPercentY(0.0095)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(1.0000)
layout:setSize({width = 274.0000, height = 634.0000})
layout:setRightMargin(822.0000)
layout:setTopMargin(-6.0000)
layout:setBottomMargin(6.0000)
container:addChild(list_games)

--Create list_detail
local list_detail = ccui.ListView:create()
list_detail:setItemsMargin(2)
list_detail:setDirection(1)
list_detail:setGravity(0)
list_detail:ignoreContentAdaptWithSize(false)
list_detail:setClippingEnabled(true)
list_detail:setBackGroundImageCapInsets({x = -4, y = -4, width = 8, height = 8})
list_detail:setBackGroundImageScale9Enabled(true)
list_detail:setLayoutComponentEnabled(true)
list_detail:setName("list_detail")
list_detail:setTag(261)
list_detail:setCascadeColorEnabled(true)
list_detail:setCascadeOpacityEnabled(true)
list_detail:setPosition(281.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(list_detail)
layout:setPositionPercentX(0.2564)
layout:setPositionPercentY(0.0158)
layout:setPercentWidth(0.7354)
layout:setPercentHeight(0.8880)
layout:setSize({width = 806.0000, height = 563.0000})
layout:setLeftMargin(281.0000)
layout:setRightMargin(9.0000)
layout:setTopMargin(61.0000)
layout:setBottomMargin(10.0000)
container:addChild(list_detail)

--Create rule_title_bg
local rule_title_bg = ccui.Layout:create()
rule_title_bg:ignoreContentAdaptWithSize(false)
rule_title_bg:setClippingEnabled(false)
rule_title_bg:setTouchEnabled(true);
rule_title_bg:setLayoutComponentEnabled(true)
rule_title_bg:setName("rule_title_bg")
rule_title_bg:setTag(468)
rule_title_bg:setCascadeColorEnabled(true)
rule_title_bg:setCascadeOpacityEnabled(true)
rule_title_bg:setAnchorPoint(0.0000, 1.0000)
rule_title_bg:setPosition(281.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(rule_title_bg)
layout:setPositionPercentX(0.2564)
layout:setPositionPercentY(1.0095)
layout:setPercentWidth(0.7345)
layout:setPercentHeight(0.0946)
layout:setSize({width = 805.0000, height = 60.0000})
layout:setLeftMargin(281.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(-6.0000)
layout:setBottomMargin(580.0000)
container:addChild(rule_title_bg)

--Create rule_title_name
local rule_title_name = ccui.Text:create()
rule_title_name:ignoreContentAdaptWithSize(true)
rule_title_name:setTextAreaSize({width = 0, height = 0})
rule_title_name:setFontName("")
rule_title_name:setFontSize(28)
rule_title_name:setString([[郑州麻将-规则]])
rule_title_name:setLayoutComponentEnabled(true)
rule_title_name:setName("rule_title_name")
rule_title_name:setTag(64)
rule_title_name:setCascadeColorEnabled(true)
rule_title_name:setCascadeOpacityEnabled(true)
rule_title_name:setAnchorPoint(0.0000, 0.5000)
rule_title_name:setPosition(30.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(rule_title_name)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0373)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2261)
layout:setPercentHeight(0.4667)
layout:setSize({width = 182.0000, height = 28.0000})
layout:setLeftMargin(30.0000)
layout:setRightMargin(593.0000)
layout:setTopMargin(16.0000)
layout:setBottomMargin(16.0000)
rule_title_bg:addChild(rule_title_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

