--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(2927)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setSize({width = 1160.0000, height = 623.0000})
layout:setLeftMargin(-580.0000)
layout:setRightMargin(-580.0000)
layout:setTopMargin(-311.5000)
layout:setBottomMargin(-311.5000)
Node:addChild(Panel_1)

--Create ing_bg
local ing_bg = ccui.ImageView:create()
ing_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
ing_bg:loadTexture("hall/common/new_pop_bg_2.png",1)
ing_bg:setScale9Enabled(true)
ing_bg:setCapInsets({x = 8, y = 70, width = 8, height = 3})
ing_bg:setLayoutComponentEnabled(true)
ing_bg:setName("ing_bg")
ing_bg:setTag(2989)
ing_bg:setCascadeColorEnabled(true)
ing_bg:setCascadeOpacityEnabled(true)
ing_bg:setPosition(580.0000, 311.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(ing_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0086)
layout:setPercentHeight(1.0161)
layout:setSize({width = 1170.0000, height = 633.0000})
layout:setLeftMargin(-5.0000)
layout:setRightMargin(-5.0000)
layout:setTopMargin(-5.0000)
layout:setBottomMargin(-5.0000)
Panel_1:addChild(ing_bg)

--Create btn_kefu
local btn_kefu = ccui.Layout:create()
btn_kefu:ignoreContentAdaptWithSize(false)
btn_kefu:setClippingEnabled(false)
btn_kefu:setBackGroundColorOpacity(102)
btn_kefu:setTouchEnabled(true);
btn_kefu:setLayoutComponentEnabled(true)
btn_kefu:setName("btn_kefu")
btn_kefu:setTag(968)
btn_kefu:setCascadeColorEnabled(true)
btn_kefu:setCascadeOpacityEnabled(true)
btn_kefu:setAnchorPoint(0.5000, 0.5000)
btn_kefu:setPosition(946.0000, 593.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_kefu)
layout:setPositionPercentX(0.8155)
layout:setPositionPercentY(0.9518)
layout:setPercentWidth(0.1483)
layout:setPercentHeight(0.0963)
layout:setSize({width = 172.0000, height = 60.0000})
layout:setLeftMargin(860.0000)
layout:setRightMargin(128.0000)
layout:setBottomMargin(563.0000)
Panel_1:addChild(btn_kefu)

--Create img_kefu
local img_kefu = ccui.ImageView:create()
img_kefu:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/bag.plist")
img_kefu:loadTexture("hall/bag/btn_kf.png",1)
img_kefu:setLayoutComponentEnabled(true)
img_kefu:setName("img_kefu")
img_kefu:setTag(969)
img_kefu:setCascadeColorEnabled(true)
img_kefu:setCascadeOpacityEnabled(true)
img_kefu:setPosition(86.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_kefu)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.6667)
layout:setSize({width = 172.0000, height = 40.0000})
layout:setTopMargin(10.0000)
layout:setBottomMargin(10.0000)
btn_kefu:addChild(img_kefu)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontSize(28)
txt_title:setString([[添加游戏]])
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(135)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setAnchorPoint(0.0000, 0.5000)
txt_title:setPosition(20.0000, 593.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setPositionPercentX(0.0172)
layout:setPositionPercentY(0.9518)
layout:setPercentWidth(0.0966)
layout:setPercentHeight(0.0449)
layout:setSize({width = 112.0000, height = 28.0000})
layout:setLeftMargin(20.0000)
layout:setRightMargin(1028.0000)
layout:setTopMargin(15.9998)
layout:setBottomMargin(579.0002)
Panel_1:addChild(txt_title)

--Create btn_close
local btn_close = ccui.Layout:create()
btn_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_close:setBackGroundImage("hall/common/new_btn_close.png",1)
btn_close:setClippingEnabled(false)
btn_close:setBackGroundColorOpacity(102)
btn_close:setTouchEnabled(true);
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(3163)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setAnchorPoint(0.5000, 0.5000)
btn_close:setPosition(1130.0000, 593.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.9741)
layout:setPositionPercentY(0.9518)
layout:setPercentWidth(0.0517)
layout:setPercentHeight(0.0963)
layout:setSize({width = 60.0000, height = 60.0000})
layout:setLeftMargin(1100.0000)
layout:setBottomMargin(563.0000)
Panel_1:addChild(btn_close)

--Create sv_bg
local sv_bg = ccui.Layout:create()
sv_bg:ignoreContentAdaptWithSize(false)
sv_bg:setClippingEnabled(true)
sv_bg:setTouchEnabled(true);
sv_bg:setLayoutComponentEnabled(true)
sv_bg:setName("sv_bg")
sv_bg:setTag(3101)
sv_bg:setCascadeColorEnabled(true)
sv_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(sv_bg)
layout:setPositionPercentXEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.9037)
layout:setSize({width = 1160.0000, height = 563.0000})
layout:setTopMargin(60.0000)
Panel_1:addChild(sv_bg)

--Create sv_addgame
local sv_addgame = ccui.ScrollView:create()
sv_addgame:setInnerContainerSize({width = 1147, height = 520})
sv_addgame:ignoreContentAdaptWithSize(false)
sv_addgame:setClippingEnabled(false)
sv_addgame:setBackGroundColorType(1)
sv_addgame:setBackGroundColor({r = 0, g = 128, b = 0})
sv_addgame:setBackGroundColorOpacity(0)
sv_addgame:setLayoutComponentEnabled(true)
sv_addgame:setName("sv_addgame")
sv_addgame:setTag(9)
sv_addgame:setCascadeColorEnabled(true)
sv_addgame:setCascadeOpacityEnabled(true)
sv_addgame:setAnchorPoint(0.5000, 1.0000)
sv_addgame:setPosition(580.0000, 520.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sv_addgame)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9236)
layout:setPercentWidth(0.9828)
layout:setPercentHeight(0.9236)
layout:setSize({width = 1140.0000, height = 520.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(10.0000)
layout:setTopMargin(43.0000)
sv_bg:addChild(sv_addgame)

--Create btn_switch
local btn_switch = ccui.Layout:create()
btn_switch:ignoreContentAdaptWithSize(false)
btn_switch:setClippingEnabled(false)
btn_switch:setBackGroundColorOpacity(102)
btn_switch:setTouchEnabled(true);
btn_switch:setLayoutComponentEnabled(true)
btn_switch:setName("btn_switch")
btn_switch:setTag(24)
btn_switch:setCascadeColorEnabled(true)
btn_switch:setCascadeOpacityEnabled(true)
btn_switch:setAnchorPoint(0.5000, 0.5000)
btn_switch:setPosition(720.0000, 593.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_switch)
layout:setPositionPercentX(0.6207)
layout:setPositionPercentY(0.9518)
layout:setPercentWidth(0.2155)
layout:setPercentHeight(0.0963)
layout:setSize({width = 250.0000, height = 60.0000})
layout:setLeftMargin(595.0000)
layout:setRightMargin(315.0000)
layout:setBottomMargin(563.0000)
Panel_1:addChild(btn_switch)

--Create txt_province
local txt_province = ccui.Text:create()
txt_province:ignoreContentAdaptWithSize(true)
txt_province:setTextAreaSize({width = 0, height = 0})
txt_province:setFontSize(30)
txt_province:setString([[黑龙江省]])
txt_province:setLayoutComponentEnabled(true)
txt_province:setName("txt_province")
txt_province:setTag(25)
txt_province:setCascadeColorEnabled(true)
txt_province:setCascadeOpacityEnabled(true)
txt_province:setAnchorPoint(1.0000, 0.5000)
txt_province:setPosition(142.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_province)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5680)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4800)
layout:setPercentHeight(0.5000)
layout:setSize({width = 120.0000, height = 30.0000})
layout:setLeftMargin(22.0000)
layout:setRightMargin(108.0000)
layout:setTopMargin(15.0000)
layout:setBottomMargin(15.0000)
btn_switch:addChild(txt_province)

--Create txt_switch
local txt_switch = ccui.Text:create()
txt_switch:ignoreContentAdaptWithSize(true)
txt_switch:setTextAreaSize({width = 0, height = 0})
txt_switch:setFontSize(30)
txt_switch:setString([==========[[切换]]==========])
txt_switch:setLayoutComponentEnabled(true)
txt_switch:setName("txt_switch")
txt_switch:setTag(89)
txt_switch:setCascadeColorEnabled(true)
txt_switch:setCascadeOpacityEnabled(true)
txt_switch:setAnchorPoint(0.0000, 0.5000)
txt_switch:setPosition(142.0000, 30.0000)
txt_switch:setTextColor({r = 252, g = 207, b = 6})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_switch)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5680)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3600)
layout:setPercentHeight(0.5000)
layout:setSize({width = 90.0000, height = 30.0000})
layout:setLeftMargin(142.0000)
layout:setRightMargin(18.0000)
layout:setTopMargin(15.0000)
layout:setBottomMargin(15.0000)
btn_switch:addChild(txt_switch)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

