--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create btn
local btn = ccui.Button:create()
btn:ignoreContentAdaptWithSize(false)
btn:loadTextureNormal("Default/Button_Normal.png",0)
btn:loadTexturePressed("Default/Button_Press.png",0)
btn:loadTextureDisabled("Default/Button_Disable.png",0)
btn:setTitleFontSize(14)
btn:setTitleColor({r = 65, g = 65, b = 70})
btn:setScale9Enabled(true)
btn:setCapInsets({x = 15, y = 11, width = 16, height = 14})
btn:setLayoutComponentEnabled(true)
btn:setName("btn")
btn:setTag(52)
btn:setCascadeColorEnabled(true)
btn:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(btn)
layout:setSize({width = 320.0000, height = 86.0000})
layout:setLeftMargin(-160.0000)
layout:setRightMargin(-160.0000)
layout:setTopMargin(-43.0000)
layout:setBottomMargin(-43.0000)
Node:addChild(btn)

--Create img_tips
local img_tips = ccui.ImageView:create()
img_tips:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
img_tips:loadTexture("hall/login/first/bg_tips.png",1)
img_tips:setScale9Enabled(true)
img_tips:setCapInsets({x = 12, y = 21, width = 116, height = 27})
img_tips:setLayoutComponentEnabled(true)
img_tips:setName("img_tips")
img_tips:setTag(67)
img_tips:setCascadeColorEnabled(true)
img_tips:setCascadeOpacityEnabled(true)
img_tips:setPosition(123.0000, 38.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_tips)
layout:setSize({width = 142.0000, height = 51.0000})
layout:setLeftMargin(52.0000)
layout:setRightMargin(-194.0000)
layout:setTopMargin(-63.5000)
layout:setBottomMargin(12.5000)
Node:addChild(img_tips)

--Create text_tips
local text_tips = ccui.Text:create()
text_tips:ignoreContentAdaptWithSize(true)
text_tips:setTextAreaSize({width = 0, height = 0})
text_tips:setFontName("")
text_tips:setFontSize(26)
text_tips:setString([[上次登录]])
text_tips:setLayoutComponentEnabled(true)
text_tips:setName("text_tips")
text_tips:setTag(68)
text_tips:setCascadeColorEnabled(true)
text_tips:setCascadeOpacityEnabled(true)
text_tips:setPosition(71.0000, 31.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(text_tips)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6078)
layout:setPercentWidth(0.7324)
layout:setPercentHeight(0.5098)
layout:setSize({width = 104.0000, height = 26.0000})
layout:setLeftMargin(19.0000)
layout:setRightMargin(19.0000)
layout:setTopMargin(7.0000)
layout:setBottomMargin(18.0000)
img_tips:addChild(text_tips)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

