--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create lay_touch
local lay_touch = ccui.Layout:create()
lay_touch:ignoreContentAdaptWithSize(false)
lay_touch:setClippingEnabled(true)
lay_touch:setBackGroundColorType(1)
lay_touch:setBackGroundColor({r = 0, g = 0, b = 0})
lay_touch:setBackGroundColorOpacity(77)
lay_touch:setTouchEnabled(true);
lay_touch:setLayoutComponentEnabled(true)
lay_touch:setName("lay_touch")
lay_touch:setTag(3867)
lay_touch:setCascadeColorEnabled(true)
lay_touch:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(lay_touch)
layout:setSize({width = 1109.0000, height = 573.0000})
layout:setRightMargin(-1109.0000)
layout:setTopMargin(-573.0000)
Node:addChild(lay_touch)

--Create search_bg
local search_bg = ccui.ImageView:create()
search_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
search_bg:loadTexture("hall/room/jxroom/search_bg.png",1)
search_bg:setScale9Enabled(true)
search_bg:setCapInsets({x = 180, y = 34, width = 1, height = 37})
search_bg:setLayoutComponentEnabled(true)
search_bg:setName("search_bg")
search_bg:setTag(91)
search_bg:setCascadeColorEnabled(true)
search_bg:setCascadeOpacityEnabled(true)
search_bg:setAnchorPoint(0.0000, 1.0000)
search_bg:setPosition(0.0000, 680.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(search_bg)
layout:setPositionPercentY(1.1867)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1832)
layout:setSize({width = 1109.0000, height = 105.0000})
layout:setTopMargin(-107.0000)
layout:setBottomMargin(575.0000)
lay_touch:addChild(search_bg)

--Create tf_bg
local tf_bg = ccui.ImageView:create()
tf_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
tf_bg:loadTexture("hall/room/jxroom/search_input_bg.png",1)
tf_bg:setScale9Enabled(true)
tf_bg:setCapInsets({x = 33, y = 33, width = 1, height = 1})
tf_bg:setLayoutComponentEnabled(true)
tf_bg:setName("tf_bg")
tf_bg:setTag(3869)
tf_bg:setCascadeColorEnabled(true)
tf_bg:setCascadeOpacityEnabled(true)
tf_bg:setAnchorPoint(0.0000, 0.5000)
tf_bg:setPosition(466.0000, 56.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(tf_bg)
layout:setPositionPercentX(0.4202)
layout:setPositionPercentY(0.5333)
layout:setPercentWidth(0.4220)
layout:setPercentHeight(0.6381)
layout:setSize({width = 468.0000, height = 67.0000})
layout:setLeftMargin(466.0000)
layout:setRightMargin(175.0000)
layout:setTopMargin(15.5000)
layout:setBottomMargin(22.5000)
search_bg:addChild(tf_bg)

--Create txt_1
local txt_1 = ccui.Text:create()
txt_1:ignoreContentAdaptWithSize(true)
txt_1:setTextAreaSize({width = 0, height = 0})
txt_1:setFontSize(30)
txt_1:setString([[查看他人回放码：]])
txt_1:setLayoutComponentEnabled(true)
txt_1:setName("txt_1")
txt_1:setTag(3870)
txt_1:setCascadeColorEnabled(true)
txt_1:setCascadeOpacityEnabled(true)
txt_1:setPosition(-125.0000, 34.0000)
txt_1:setTextColor({r = 213, g = 157, b = 99})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_1)
layout:setPositionPercentX(-0.2671)
layout:setPositionPercentY(0.5075)
layout:setPercentWidth(0.5128)
layout:setPercentHeight(0.4478)
layout:setSize({width = 240.0000, height = 30.0000})
layout:setLeftMargin(-245.0000)
layout:setRightMargin(473.0000)
layout:setTopMargin(18.0000)
layout:setBottomMargin(19.0000)
tf_bg:addChild(txt_1)

--Create btn_search
local btn_search = ccui.Button:create()
btn_search:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
btn_search:loadTextureNormal("hall/room/jxroom/search_btn.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
btn_search:loadTexturePressed("hall/room/jxroom/search_btn.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
btn_search:loadTextureDisabled("hall/room/jxroom/search_btn.png",1)
btn_search:setTitleFontSize(14)
btn_search:setTitleColor({r = 65, g = 65, b = 70})
btn_search:setScale9Enabled(true)
btn_search:setCapInsets({x = 15, y = 11, width = 114, height = 42})
btn_search:setLayoutComponentEnabled(true)
btn_search:setName("btn_search")
btn_search:setTag(92)
btn_search:setCascadeColorEnabled(true)
btn_search:setCascadeOpacityEnabled(true)
btn_search:setPosition(554.0000, 33.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_search)
layout:setPositionPercentX(1.1838)
layout:setPositionPercentY(0.4925)
layout:setPercentWidth(0.3077)
layout:setPercentHeight(0.9552)
layout:setSize({width = 144.0000, height = 64.0000})
layout:setLeftMargin(482.0000)
layout:setRightMargin(-158.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(1.0000)
tf_bg:addChild(btn_search)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

