--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/recordstatistics.plist")
Image_1:loadTexture("hall/recordstatistics/user_name_bg.png",1)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 5, y = 5, width = 6, height = 6})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(80)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setSize({width = 205.0000, height = 76.0000})
layout:setRightMargin(-205.0000)
layout:setTopMargin(-76.0000)
Node:addChild(Image_1)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/recordstatistics.plist")
Image_2:loadTexture("hall/recordstatistics/user_name_bg.png",1)
Image_2:setScale9Enabled(true)
Image_2:setCapInsets({x = 5, y = 5, width = 6, height = 6})
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(41)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setVisible(false)
Image_2:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setSize({width = 238.0000, height = 76.0000})
layout:setRightMargin(-238.0000)
layout:setTopMargin(-76.0000)
Node:addChild(Image_2)

--Create txt_uid
local txt_uid = ccui.Text:create()
txt_uid:ignoreContentAdaptWithSize(true)
txt_uid:setTextAreaSize({width = 0, height = 0})
txt_uid:setFontName("")
txt_uid:setFontSize(18)
txt_uid:setString([[123456789]])
txt_uid:setTextHorizontalAlignment(1)
txt_uid:setTextVerticalAlignment(1)
txt_uid:setLayoutComponentEnabled(true)
txt_uid:setName("txt_uid")
txt_uid:setTag(85)
txt_uid:setCascadeColorEnabled(true)
txt_uid:setCascadeOpacityEnabled(true)
txt_uid:setAnchorPoint(0.0000, 0.5000)
txt_uid:setPosition(66.5055, 23.0438)
txt_uid:setTextColor({r = 119, g = 119, b = 119})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_uid)
layout:setSize({width = 81.0000, height = 18.0000})
layout:setLeftMargin(66.5055)
layout:setRightMargin(-147.5055)
layout:setTopMargin(-32.0438)
layout:setBottomMargin(14.0438)
Node:addChild(txt_uid)

--Create txt_uname
local txt_uname = ccui.Text:create()
txt_uname:ignoreContentAdaptWithSize(true)
txt_uname:setTextAreaSize({width = 0, height = 0})
txt_uname:setFontName("")
txt_uname:setFontSize(20)
txt_uname:setString([[玩家名字]])
txt_uname:setTextHorizontalAlignment(1)
txt_uname:setTextVerticalAlignment(1)
txt_uname:setLayoutComponentEnabled(true)
txt_uname:setName("txt_uname")
txt_uname:setTag(86)
txt_uname:setCascadeColorEnabled(true)
txt_uname:setCascadeOpacityEnabled(true)
txt_uname:setAnchorPoint(0.0000, 0.5000)
txt_uname:setPosition(69.5051, 46.7690)
txt_uname:setTextColor({r = 34, g = 34, b = 34})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_uname)
layout:setSize({width = 80.0000, height = 20.0000})
layout:setLeftMargin(69.5051)
layout:setRightMargin(-149.5051)
layout:setTopMargin(-56.7690)
layout:setBottomMargin(36.7690)
Node:addChild(txt_uname)

--Create img_avatar
local img_avatar = ccui.ImageView:create()
img_avatar:ignoreContentAdaptWithSize(false)
img_avatar:loadTexture("Default/ImageFile.png",0)
img_avatar:setLayoutComponentEnabled(true)
img_avatar:setName("img_avatar")
img_avatar:setTag(87)
img_avatar:setCascadeColorEnabled(true)
img_avatar:setCascadeOpacityEnabled(true)
img_avatar:setAnchorPoint(0.0000, 0.5000)
img_avatar:setPosition(16.7900, 36.7449)
layout = ccui.LayoutComponent:bindLayoutComponent(img_avatar)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(16.7900)
layout:setRightMargin(-62.7900)
layout:setTopMargin(-59.7449)
layout:setBottomMargin(13.7449)
Node:addChild(img_avatar)

--Create txt_score
local txt_score = ccui.Text:create()
txt_score:ignoreContentAdaptWithSize(true)
txt_score:setTextAreaSize({width = 0, height = 0})
txt_score:setFontName("")
txt_score:setFontSize(30)
txt_score:setString([[-21]])
txt_score:setLayoutComponentEnabled(true)
txt_score:setName("txt_score")
txt_score:setTag(79)
txt_score:setCascadeColorEnabled(true)
txt_score:setCascadeOpacityEnabled(true)
txt_score:setAnchorPoint(1.0000, 0.5000)
txt_score:setPosition(204.1944, 36.0356)
txt_score:setTextColor({r = 72, g = 147, b = 233})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_score)
layout:setSize({width = 45.0000, height = 30.0000})
layout:setLeftMargin(159.1944)
layout:setRightMargin(-204.1944)
layout:setTopMargin(-51.0356)
layout:setBottomMargin(21.0356)
Node:addChild(txt_score)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

