--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_icon
local img_icon = ccui.ImageView:create()
img_icon:ignoreContentAdaptWithSize(false)
img_icon:loadTexture("Default/ImageFile.png",0)
img_icon:setTouchEnabled(true);
img_icon:setLayoutComponentEnabled(true)
img_icon:setName("img_icon")
img_icon:setTag(69)
img_icon:setCascadeColorEnabled(true)
img_icon:setCascadeOpacityEnabled(true)
img_icon:setPosition(0.0000, 4.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_icon)
layout:setSize({width = 100.0000, height = 100.0000})
layout:setLeftMargin(-50.0000)
layout:setRightMargin(-50.0000)
layout:setTopMargin(-54.0000)
layout:setBottomMargin(-46.0000)
Node:addChild(img_icon)

--Create txt_count
local txt_count = ccui.TextBMFont:create()
txt_count:setFntFile("fonts/bag_props_num.fnt")
txt_count:setString([[0]])
txt_count:setLayoutComponentEnabled(true)
txt_count:setName("txt_count")
txt_count:setTag(2608)
txt_count:setCascadeColorEnabled(true)
txt_count:setCascadeOpacityEnabled(true)
txt_count:setAnchorPoint(1.0000, 0.5000)
txt_count:setPosition(49.0000, -40.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_count)
layout:setSize({width = 16.0000, height = 25.0000})
layout:setLeftMargin(33.0000)
layout:setRightMargin(-49.0000)
layout:setTopMargin(27.5000)
layout:setBottomMargin(-52.5000)
Node:addChild(txt_count)

--Create img_jpq1
local img_jpq1 = ccui.ImageView:create()
img_jpq1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/bag.plist")
img_jpq1:loadTexture("hall/bag/img_time2.png",1)
img_jpq1:setLayoutComponentEnabled(true)
img_jpq1:setName("img_jpq1")
img_jpq1:setTag(2363)
img_jpq1:setCascadeColorEnabled(true)
img_jpq1:setCascadeOpacityEnabled(true)
img_jpq1:setVisible(false)
img_jpq1:setPosition(2.3320, -40.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_jpq1)
layout:setSize({width = 24.0000, height = 24.0000})
layout:setLeftMargin(-9.6680)
layout:setRightMargin(-14.3320)
layout:setTopMargin(28.0000)
layout:setBottomMargin(-52.0000)
Node:addChild(img_jpq1)

--Create panel_jpq
local panel_jpq = ccui.Layout:create()
panel_jpq:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/bag.plist")
panel_jpq:setBackGroundImage("hall/bag/jqp_di.png",1)
panel_jpq:setClippingEnabled(false)
panel_jpq:setBackGroundColorOpacity(247)
panel_jpq:setTouchEnabled(true);
panel_jpq:setLayoutComponentEnabled(true)
panel_jpq:setName("panel_jpq")
panel_jpq:setTag(2360)
panel_jpq:setCascadeColorEnabled(true)
panel_jpq:setCascadeOpacityEnabled(true)
panel_jpq:setVisible(false)
panel_jpq:setPosition(-52.5000, 22.4800)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_jpq)
layout:setSize({width = 85.0000, height = 31.0000})
layout:setLeftMargin(-52.5000)
layout:setRightMargin(-32.5000)
layout:setTopMargin(-53.4800)
layout:setBottomMargin(22.4800)
Node:addChild(panel_jpq)

--Create img_jpq
local img_jpq = ccui.ImageView:create()
img_jpq:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/bag.plist")
img_jpq:loadTexture("hall/bag/img_time.png",1)
img_jpq:setLayoutComponentEnabled(true)
img_jpq:setName("img_jpq")
img_jpq:setTag(2361)
img_jpq:setCascadeColorEnabled(true)
img_jpq:setCascadeOpacityEnabled(true)
img_jpq:setPosition(14.1431, 15.0574)
layout = ccui.LayoutComponent:bindLayoutComponent(img_jpq)
layout:setPositionPercentX(0.1664)
layout:setPositionPercentY(0.4857)
layout:setPercentWidth(0.2588)
layout:setPercentHeight(0.7097)
layout:setSize({width = 22.0000, height = 22.0000})
layout:setLeftMargin(3.1431)
layout:setRightMargin(59.8569)
layout:setTopMargin(4.9426)
layout:setBottomMargin(4.0574)
panel_jpq:addChild(img_jpq)

--Create txt_jpq_count
local txt_jpq_count = ccui.TextBMFont:create()
txt_jpq_count:setFntFile("fonts/bag_props_num.fnt")
txt_jpq_count:setString([[3天]])
txt_jpq_count:setLayoutComponentEnabled(true)
txt_jpq_count:setName("txt_jpq_count")
txt_jpq_count:setTag(2362)
txt_jpq_count:setCascadeColorEnabled(true)
txt_jpq_count:setCascadeOpacityEnabled(true)
txt_jpq_count:setAnchorPoint(0.0000, 0.5000)
txt_jpq_count:setPosition(32.8746, 15.0239)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_jpq_count)
layout:setPositionPercentX(0.3868)
layout:setPositionPercentY(0.4846)
layout:setPercentWidth(0.5059)
layout:setPercentHeight(0.8065)
layout:setSize({width = 43.0000, height = 25.0000})
layout:setLeftMargin(32.8746)
layout:setRightMargin(9.1254)
layout:setTopMargin(3.4761)
layout:setBottomMargin(2.5239)
panel_jpq:addChild(txt_jpq_count)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

