--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_bg
local img_bg = ccui.Layout:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:setClippingEnabled(false)
img_bg:setBackGroundColorType(1)
img_bg:setBackGroundColor({r = 0, g = 0, b = 0})
img_bg:setBackGroundColorOpacity(153)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(42)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 1280.0000, height = 60.0000})
layout:setRightMargin(-1280.0000)
layout:setTopMargin(-60.0000)
Node:addChild(img_bg)

--Create panel_message
local panel_message = ccui.Layout:create()
panel_message:ignoreContentAdaptWithSize(false)
panel_message:setClippingEnabled(true)
panel_message:setBackGroundColorType(1)
panel_message:setBackGroundColor({r = 150, g = 200, b = 255})
panel_message:setBackGroundColorOpacity(0)
panel_message:setLayoutComponentEnabled(true)
panel_message:setName("panel_message")
panel_message:setTag(334)
panel_message:setCascadeColorEnabled(true)
panel_message:setCascadeOpacityEnabled(true)
panel_message:setPosition(0.0000, 5.3400)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_message)
layout:setPositionPercentY(0.0890)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.5833)
layout:setSize({width = 1280.0000, height = 35.0000})
layout:setTopMargin(19.6600)
layout:setBottomMargin(5.3400)
img_bg:addChild(panel_message)

--Create txt_message
local txt_message = ccui.Text:create()
txt_message:ignoreContentAdaptWithSize(true)
txt_message:setTextAreaSize({width = 0, height = 0})
txt_message:setFontSize(25)
txt_message:setString([[GM9000 在牌局中居然打出了【连七对】的番型，系统奖励了7588开心豆。]])
txt_message:setLayoutComponentEnabled(true)
txt_message:setName("txt_message")
txt_message:setTag(335)
txt_message:setCascadeColorEnabled(true)
txt_message:setCascadeOpacityEnabled(true)
txt_message:setVisible(false)
txt_message:setAnchorPoint(0.0000, 0.5000)
txt_message:setPosition(16.0002, 16.8800)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_message)
layout:setPositionPercentX(0.0125)
layout:setPositionPercentY(0.4823)
layout:setPercentWidth(0.6391)
layout:setPercentHeight(0.7143)
layout:setSize({width = 818.0000, height = 25.0000})
layout:setLeftMargin(16.0002)
layout:setRightMargin(445.9998)
layout:setTopMargin(5.6200)
layout:setBottomMargin(4.3800)
panel_message:addChild(txt_message)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

