--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_bg
local Panel_bg = ccui.Layout:create()
Panel_bg:ignoreContentAdaptWithSize(false)
Panel_bg:setClippingEnabled(false)
Panel_bg:setTouchEnabled(true);
Panel_bg:setLayoutComponentEnabled(true)
Panel_bg:setName("Panel_bg")
Panel_bg:setTag(662)
Panel_bg:setCascadeColorEnabled(true)
Panel_bg:setCascadeOpacityEnabled(true)
Panel_bg:setAnchorPoint(0.5000, 0.5000)
Panel_bg:setPosition(0.0000, 20.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_bg)
layout:setSize({width = 1044.0000, height = 585.0000})
layout:setLeftMargin(-522.0000)
layout:setRightMargin(-522.0000)
layout:setTopMargin(-312.5000)
layout:setBottomMargin(-272.5000)
Node:addChild(Panel_bg)

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("hall/welfare/sign/img_mrqd_bg.png",0)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(824)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setPosition(522.0000, 292.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0383)
layout:setPercentHeight(1.0513)
layout:setSize({width = 1084.0000, height = 615.0000})
layout:setLeftMargin(-20.0000)
layout:setRightMargin(-20.0000)
layout:setTopMargin(-15.0000)
layout:setBottomMargin(-15.0000)
Panel_bg:addChild(img_bg)

--Create btn_close
local btn_close = ccui.Layout:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:setClippingEnabled(false)
btn_close:setTouchEnabled(true);
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(664)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setAnchorPoint(0.5000, 0.5000)
btn_close:setPosition(1090.8750, 562.5360)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(1.0449)
layout:setPositionPercentY(0.9616)
layout:setPercentWidth(0.0766)
layout:setPercentHeight(0.1368)
layout:setSize({width = 80.0000, height = 80.0000})
layout:setLeftMargin(1050.8750)
layout:setRightMargin(-86.8755)
layout:setTopMargin(-17.5360)
layout:setBottomMargin(522.5360)
Panel_bg:addChild(btn_close)

--Create img1
local img1 = ccui.ImageView:create()
img1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/sign.plist")
img1:loadTexture("hall/welfare/sign/close.png",1)
img1:setLayoutComponentEnabled(true)
img1:setName("img1")
img1:setTag(665)
img1:setCascadeColorEnabled(true)
img1:setCascadeOpacityEnabled(true)
img1:setPosition(40.0000, 40.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5000)
layout:setPercentHeight(0.5000)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(20.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(20.0000)
layout:setBottomMargin(20.0000)
btn_close:addChild(img1)

--Create sv_mrqd
local sv_mrqd = ccui.ScrollView:create()
sv_mrqd:setBounceEnabled(true)
sv_mrqd:setInnerContainerSize({width = 880, height = 446})
sv_mrqd:ignoreContentAdaptWithSize(false)
sv_mrqd:setClippingEnabled(true)
sv_mrqd:setBackGroundColorOpacity(156)
sv_mrqd:setLayoutComponentEnabled(true)
sv_mrqd:setName("sv_mrqd")
sv_mrqd:setTag(668)
sv_mrqd:setCascadeColorEnabled(true)
sv_mrqd:setCascadeOpacityEnabled(true)
sv_mrqd:setAnchorPoint(0.5000, 1.0000)
sv_mrqd:setPosition(522.0000, 458.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(sv_mrqd)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7838)
layout:setPercentWidth(0.8333)
layout:setPercentHeight(0.7624)
layout:setSize({width = 870.0000, height = 446.0000})
layout:setLeftMargin(87.0000)
layout:setRightMargin(87.0000)
layout:setTopMargin(126.5000)
layout:setBottomMargin(12.5000)
Panel_bg:addChild(sv_mrqd)

--Create txt_hint
local txt_hint = ccui.Text:create()
txt_hint:ignoreContentAdaptWithSize(true)
txt_hint:setTextAreaSize({width = 0, height = 0})
txt_hint:setFontSize(28)
txt_hint:setString([[数据加载失败，请关闭窗口重试]])
txt_hint:setLayoutComponentEnabled(true)
txt_hint:setName("txt_hint")
txt_hint:setTag(87)
txt_hint:setCascadeColorEnabled(true)
txt_hint:setCascadeOpacityEnabled(true)
txt_hint:setVisible(false)
txt_hint:setPosition(521.3149, 222.9900)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_hint)
layout:setPositionPercentX(0.4993)
layout:setPositionPercentY(0.3812)
layout:setPercentWidth(0.3755)
layout:setPercentHeight(0.0479)
layout:setSize({width = 392.0000, height = 28.0000})
layout:setLeftMargin(325.3149)
layout:setRightMargin(326.6851)
layout:setTopMargin(348.0100)
layout:setBottomMargin(208.9900)
Panel_bg:addChild(txt_hint)

--Create txt_data
local txt_data = ccui.Text:create()
txt_data:ignoreContentAdaptWithSize(true)
txt_data:setTextAreaSize({width = 0, height = 0})
txt_data:setFontSize(28)
txt_data:setString([[数据加载中...]])
txt_data:setLayoutComponentEnabled(true)
txt_data:setName("txt_data")
txt_data:setTag(1267)
txt_data:setCascadeColorEnabled(true)
txt_data:setCascadeOpacityEnabled(true)
txt_data:setPosition(521.3100, 223.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_data)
layout:setPositionPercentX(0.4993)
layout:setPositionPercentY(0.3812)
layout:setPercentWidth(0.1743)
layout:setPercentHeight(0.0479)
layout:setSize({width = 182.0000, height = 28.0000})
layout:setLeftMargin(430.3100)
layout:setRightMargin(431.6900)
layout:setTopMargin(348.0000)
layout:setBottomMargin(209.0000)
Panel_bg:addChild(txt_data)

--Create img_base
local img_base = ccui.ImageView:create()
img_base:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/sign.plist")
img_base:loadTexture("hall/welfare/sign/img_4.png",1)
img_base:setScale9Enabled(true)
img_base:setCapInsets({x = 77, y = 4, width = 8, height = 1})
img_base:setLayoutComponentEnabled(true)
img_base:setName("img_base")
img_base:setTag(1961)
img_base:setCascadeColorEnabled(true)
img_base:setCascadeOpacityEnabled(true)
img_base:setAnchorPoint(0.5000, 0.0000)
img_base:setPosition(522.0000, 13.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_base)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0222)
layout:setPercentWidth(0.8333)
layout:setPercentHeight(0.0171)
layout:setSize({width = 870.0000, height = 10.0000})
layout:setLeftMargin(87.0000)
layout:setRightMargin(87.0000)
layout:setTopMargin(562.0000)
layout:setBottomMargin(13.0000)
Panel_bg:addChild(img_base)

--Create img_top
local img_top = ccui.ImageView:create()
img_top:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/sign.plist")
img_top:loadTexture("hall/welfare/sign/img_4.png",1)
img_top:setFlippedY(true)
img_top:setScale9Enabled(true)
img_top:setCapInsets({x = 77, y = 4, width = 8, height = 1})
img_top:setLayoutComponentEnabled(true)
img_top:setName("img_top")
img_top:setTag(2108)
img_top:setCascadeColorEnabled(true)
img_top:setCascadeOpacityEnabled(true)
img_top:setAnchorPoint(0.5000, 0.0000)
img_top:setPosition(522.0000, 458.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_top)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7829)
layout:setPercentWidth(0.8333)
layout:setPercentHeight(0.0171)
layout:setSize({width = 870.0000, height = 10.0000})
layout:setLeftMargin(87.0000)
layout:setRightMargin(87.0000)
layout:setTopMargin(117.0000)
layout:setBottomMargin(458.0000)
Panel_bg:addChild(img_top)

--Create vip_btn
local vip_btn = ccui.Button:create()
vip_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/sign.plist")
vip_btn:loadTextureNormal("hall/welfare/sign/vipxiangqing.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/sign.plist")
vip_btn:loadTexturePressed("hall/welfare/sign/vipxiangqing.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/sign.plist")
vip_btn:loadTextureDisabled("hall/welfare/sign/vipxiangqing.png",1)
vip_btn:setTitleFontSize(14)
vip_btn:setTitleColor({r = 65, g = 65, b = 70})
vip_btn:setScale9Enabled(true)
vip_btn:setCapInsets({x = 15, y = 11, width = 98, height = 5})
vip_btn:setLayoutComponentEnabled(true)
vip_btn:setName("vip_btn")
vip_btn:setTag(125)
vip_btn:setCascadeColorEnabled(true)
vip_btn:setCascadeOpacityEnabled(true)
vip_btn:setPosition(216.2928, 503.6178)
layout = ccui.LayoutComponent:bindLayoutComponent(vip_btn)
layout:setPositionPercentX(0.2072)
layout:setPositionPercentY(0.8609)
layout:setPercentWidth(0.1226)
layout:setPercentHeight(0.0462)
layout:setSize({width = 128.0000, height = 27.0000})
layout:setLeftMargin(152.2928)
layout:setRightMargin(763.7072)
layout:setTopMargin(67.8822)
layout:setBottomMargin(490.1178)
Panel_bg:addChild(vip_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

