--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_bg:loadTexture("hall/common/new_pop_bg_2.png",1)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 7, y = 70, width = 10, height = 3})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(82)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 1224.0000, height = 670.0000})
layout:setLeftMargin(-612.0000)
layout:setRightMargin(-612.0000)
layout:setTopMargin(-335.0000)
layout:setBottomMargin(-335.0000)
Node:addChild(img_bg)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontSize(28)
txt_title:setString([[选择您所在的地区：]])
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(98)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setAnchorPoint(0.0000, 0.5000)
txt_title:setPosition(30.0000, 633.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setPositionPercentX(0.0245)
layout:setPositionPercentY(0.9448)
layout:setPercentWidth(0.2059)
layout:setPercentHeight(0.0418)
layout:setSize({width = 252.0000, height = 28.0000})
layout:setLeftMargin(30.0000)
layout:setRightMargin(942.0000)
layout:setTopMargin(23.0000)
layout:setBottomMargin(619.0000)
img_bg:addChild(txt_title)

--Create txt_area
local txt_area = ccui.Text:create()
txt_area:ignoreContentAdaptWithSize(true)
txt_area:setTextAreaSize({width = 0, height = 0})
txt_area:setFontSize(36)
txt_area:setString([[全国>>]])
txt_area:setLayoutComponentEnabled(true)
txt_area:setName("txt_area")
txt_area:setTag(99)
txt_area:setCascadeColorEnabled(true)
txt_area:setCascadeOpacityEnabled(true)
txt_area:setAnchorPoint(0.0000, 0.5000)
txt_area:setPosition(30.0000, 565.0000)
txt_area:setTextColor({r = 102, g = 102, b = 102})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_area)
layout:setPositionPercentX(0.0245)
layout:setPositionPercentY(0.8433)
layout:setPercentWidth(0.0882)
layout:setPercentHeight(0.0537)
layout:setSize({width = 108.0000, height = 36.0000})
layout:setLeftMargin(30.0000)
layout:setRightMargin(1086.0000)
layout:setTopMargin(87.0000)
layout:setBottomMargin(547.0000)
img_bg:addChild(txt_area)

--Create pv
local pv = ccui.PageView:create()
pv:ignoreContentAdaptWithSize(false)
pv:setClippingEnabled(true)
pv:setBackGroundColorOpacity(119)
pv:setLayoutComponentEnabled(true)
pv:setName("pv")
pv:setTag(102)
pv:setCascadeColorEnabled(true)
pv:setCascadeOpacityEnabled(true)
pv:setAnchorPoint(0.5000, 0.5000)
pv:setPosition(612.0000, 325.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(pv)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4851)
layout:setPercentWidth(0.9804)
layout:setPercentHeight(0.5970)
layout:setSize({width = 1200.0000, height = 400.0000})
layout:setLeftMargin(12.0000)
layout:setRightMargin(12.0000)
layout:setTopMargin(145.0000)
layout:setBottomMargin(125.0000)
img_bg:addChild(pv)

--Create panel_back
local panel_back = ccui.Layout:create()
panel_back:ignoreContentAdaptWithSize(false)
panel_back:setClippingEnabled(false)
panel_back:setBackGroundColorType(1)
panel_back:setBackGroundColor({r = 150, g = 200, b = 255})
panel_back:setBackGroundColorOpacity(0)
panel_back:setTouchEnabled(true);
panel_back:setLayoutComponentEnabled(true)
panel_back:setName("panel_back")
panel_back:setTag(100)
panel_back:setCascadeColorEnabled(true)
panel_back:setCascadeOpacityEnabled(true)
panel_back:setAnchorPoint(1.0000, 0.5000)
panel_back:setPosition(1210.0000, 565.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_back)
layout:setPositionPercentX(0.9886)
layout:setPositionPercentY(0.8433)
layout:setPercentWidth(0.1307)
layout:setPercentHeight(0.0896)
layout:setSize({width = 160.0000, height = 60.0000})
layout:setLeftMargin(1050.0000)
layout:setRightMargin(14.0000)
layout:setTopMargin(75.0000)
layout:setBottomMargin(535.0000)
img_bg:addChild(panel_back)

--Create txt_fh
local txt_fh = ccui.Text:create()
txt_fh:ignoreContentAdaptWithSize(true)
txt_fh:setTextAreaSize({width = 0, height = 0})
txt_fh:setFontSize(36)
txt_fh:setString([[<<返回]])
txt_fh:setLayoutComponentEnabled(true)
txt_fh:setName("txt_fh")
txt_fh:setTag(101)
txt_fh:setCascadeColorEnabled(true)
txt_fh:setCascadeOpacityEnabled(true)
txt_fh:setAnchorPoint(0.0000, 0.5000)
txt_fh:setPosition(30.0000, 30.0000)
txt_fh:setTextColor({r = 14, g = 144, b = 212})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_fh)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1875)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6750)
layout:setPercentHeight(0.6000)
layout:setSize({width = 108.0000, height = 36.0000})
layout:setLeftMargin(30.0000)
layout:setRightMargin(22.0000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(12.0000)
panel_back:addChild(txt_fh)

--Create btn_join_game
local btn_join_game = ccui.Button:create()
btn_join_game:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_join_game:loadTextureNormal("hall/common/new_btn_noangle.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_join_game:loadTexturePressed("hall/common/new_btn_noangle.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_join_game:loadTextureDisabled("hall/common/new_btn_noangle.png",1)
btn_join_game:setTitleFontSize(14)
btn_join_game:setTitleColor({r = 65, g = 65, b = 70})
btn_join_game:setScale9Enabled(true)
btn_join_game:setCapInsets({x = 5, y = 5, width = 8, height = 8})
btn_join_game:setLayoutComponentEnabled(true)
btn_join_game:setName("btn_join_game")
btn_join_game:setTag(103)
btn_join_game:setCascadeColorEnabled(true)
btn_join_game:setCascadeOpacityEnabled(true)
btn_join_game:setPosition(612.0000, 72.7626)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_join_game)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1086)
layout:setPercentWidth(0.3431)
layout:setPercentHeight(0.1119)
layout:setSize({width = 420.0000, height = 75.0000})
layout:setLeftMargin(402.0000)
layout:setRightMargin(402.0000)
layout:setTopMargin(559.7374)
layout:setBottomMargin(35.2626)
img_bg:addChild(btn_join_game)

--Create btn_bg
local btn_bg = ccui.ImageView:create()
btn_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_bg:loadTexture("hall/common/new_btn_noangle.png",1)
btn_bg:setScale9Enabled(true)
btn_bg:setCapInsets({x = 5, y = 5, width = 8, height = 8})
btn_bg:setLayoutComponentEnabled(true)
btn_bg:setName("btn_bg")
btn_bg:setTag(23)
btn_bg:setCascadeColorEnabled(true)
btn_bg:setCascadeOpacityEnabled(true)
btn_bg:setPosition(210.0000, 37.5000)
btn_bg:setColor({r = 46, g = 153, b = 11})
layout = ccui.LayoutComponent:bindLayoutComponent(btn_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 420.0000, height = 75.0000})
btn_join_game:addChild(btn_bg)

--Create btn_name
local btn_name = ccui.Text:create()
btn_name:ignoreContentAdaptWithSize(true)
btn_name:setTextAreaSize({width = 0, height = 0})
btn_name:setFontSize(36)
btn_name:setString([[进入游戏]])
btn_name:setLayoutComponentEnabled(true)
btn_name:setName("btn_name")
btn_name:setTag(104)
btn_name:setCascadeColorEnabled(true)
btn_name:setCascadeOpacityEnabled(true)
btn_name:setPosition(210.0000, 37.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_name)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3429)
layout:setPercentHeight(0.4800)
layout:setSize({width = 144.0000, height = 36.0000})
layout:setLeftMargin(138.0000)
layout:setRightMargin(138.0000)
layout:setTopMargin(19.5000)
layout:setBottomMargin(19.5000)
btn_join_game:addChild(btn_name)

--Create btn_close
local btn_close = ccui.Layout:create()
btn_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_close:setBackGroundImage("hall/common/new_btn_close.png",1)
btn_close:setClippingEnabled(false)
btn_close:setBackGroundColorOpacity(102)
btn_close:setTouchEnabled(true);
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(132)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setAnchorPoint(0.5000, 0.5000)
btn_close:setPosition(1184.0000, 635.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.9673)
layout:setPositionPercentY(0.9478)
layout:setPercentWidth(0.0572)
layout:setPercentHeight(0.1045)
layout:setSize({width = 70.0000, height = 70.0000})
layout:setLeftMargin(1149.0000)
layout:setRightMargin(5.0000)
layout:setBottomMargin(600.0000)
img_bg:addChild(btn_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

