--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_item_bg
local img_item_bg = ccui.ImageView:create()
img_item_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/lotto.plist")
img_item_bg:loadTexture("hall/lotto/item_bg.png",1)
img_item_bg:setLayoutComponentEnabled(true)
img_item_bg:setName("img_item_bg")
img_item_bg:setTag(1042)
img_item_bg:setCascadeColorEnabled(true)
img_item_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_item_bg)
layout:setSize({width = 176.0000, height = 186.0000})
layout:setLeftMargin(-88.0000)
layout:setRightMargin(-88.0000)
layout:setTopMargin(-93.0000)
layout:setBottomMargin(-93.0000)
Node:addChild(img_item_bg)

--Create img_light
local img_light = ccui.ImageView:create()
img_light:ignoreContentAdaptWithSize(false)
img_light:loadTexture("hall/lotto/light.png",0)
img_light:setLayoutComponentEnabled(true)
img_light:setName("img_light")
img_light:setTag(1041)
img_light:setCascadeColorEnabled(true)
img_light:setCascadeOpacityEnabled(true)
img_light:setAnchorPoint(0.5109, 0.5187)
layout = ccui.LayoutComponent:bindLayoutComponent(img_light)
layout:setSize({width = 813.0000, height = 695.0000})
layout:setLeftMargin(-415.3617)
layout:setRightMargin(-397.6383)
layout:setTopMargin(-334.5035)
layout:setBottomMargin(-360.4965)
Node:addChild(img_light)

--Create img_prop
local img_prop = ccui.ImageView:create()
img_prop:ignoreContentAdaptWithSize(false)
img_prop:loadTexture("common/prop/img_prop_yuanbao.png",0)
img_prop:setLayoutComponentEnabled(true)
img_prop:setName("img_prop")
img_prop:setTag(1043)
img_prop:setCascadeColorEnabled(true)
img_prop:setCascadeOpacityEnabled(true)
img_prop:setPosition(0.0000, 19.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_prop)
layout:setSize({width = 132.0000, height = 82.0000})
layout:setLeftMargin(-66.0000)
layout:setRightMargin(-66.0000)
layout:setTopMargin(-60.0000)
layout:setBottomMargin(-22.0000)
Node:addChild(img_prop)

--Create txt_cnt
local txt_cnt = ccui.Text:create()
txt_cnt:ignoreContentAdaptWithSize(true)
txt_cnt:setTextAreaSize({width = 0, height = 0})
txt_cnt:setFontSize(32)
txt_cnt:setString([[x1000]])
txt_cnt:enableOutline({r = 255, g = 255, b = 255, a = 255}, 2)
txt_cnt:setLayoutComponentEnabled(true)
txt_cnt:setName("txt_cnt")
txt_cnt:setTag(1044)
txt_cnt:setCascadeColorEnabled(true)
txt_cnt:setCascadeOpacityEnabled(true)
txt_cnt:setPosition(0.0000, -50.0000)
txt_cnt:setTextColor({r = 212, g = 39, b = 15})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_cnt)
layout:setSize({width = 87.0000, height = 41.0000})
layout:setLeftMargin(-43.5000)
layout:setRightMargin(-43.5000)
layout:setTopMargin(29.5000)
layout:setBottomMargin(-70.5000)
Node:addChild(txt_cnt)

--Create img_gxhd
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/lotto.plist")
local img_gxhd = cc.Sprite:createWithSpriteFrameName("hall/lotto/img_gxhd.png")
img_gxhd:setName("img_gxhd")
img_gxhd:setTag(1045)
img_gxhd:setCascadeColorEnabled(true)
img_gxhd:setCascadeOpacityEnabled(true)
img_gxhd:setPosition(0.0000, 185.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_gxhd)
layout:setSize({width = 275.0000, height = 74.0000})
layout:setLeftMargin(-137.5000)
layout:setRightMargin(-137.5000)
layout:setTopMargin(-222.0000)
layout:setBottomMargin(148.0000)
img_gxhd:setBlendFunc({src = 1, dst = 771})
Node:addChild(img_gxhd)

--Create btn_share
local btn_share = ccui.Layout:create()
btn_share:ignoreContentAdaptWithSize(false)
btn_share:setClippingEnabled(false)
btn_share:setTouchEnabled(true);
btn_share:setLayoutComponentEnabled(true)
btn_share:setName("btn_share")
btn_share:setTag(693)
btn_share:setCascadeColorEnabled(true)
btn_share:setCascadeOpacityEnabled(true)
btn_share:setAnchorPoint(0.5000, 0.5000)
btn_share:setPosition(-140.0000, -186.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_share)
layout:setSize({width = 210.0000, height = 70.0000})
layout:setLeftMargin(-245.0000)
layout:setRightMargin(35.0000)
layout:setTopMargin(151.0000)
layout:setBottomMargin(-221.0000)
Node:addChild(btn_share)

--Create btn_bg
local btn_bg = ccui.ImageView:create()
btn_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_bg:loadTexture("hall/common/new_btn_noangle.png",1)
btn_bg:setScale9Enabled(true)
btn_bg:setCapInsets({x = 8, y = 8, width = 2, height = 2})
btn_bg:setLayoutComponentEnabled(true)
btn_bg:setName("btn_bg")
btn_bg:setTag(1479)
btn_bg:setCascadeColorEnabled(true)
btn_bg:setCascadeOpacityEnabled(true)
btn_bg:setPosition(105.0000, 35.0000)
btn_bg:setColor({r = 38, g = 155, b = 88})
layout = ccui.LayoutComponent:bindLayoutComponent(btn_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 210.0000, height = 70.0000})
btn_share:addChild(btn_bg)

--Create btn_name
local btn_name = ccui.Text:create()
btn_name:ignoreContentAdaptWithSize(true)
btn_name:setTextAreaSize({width = 0, height = 0})
btn_name:setFontSize(36)
btn_name:setString([[分享]])
btn_name:setLayoutComponentEnabled(true)
btn_name:setName("btn_name")
btn_name:setTag(694)
btn_name:setCascadeColorEnabled(true)
btn_name:setCascadeOpacityEnabled(true)
btn_name:setPosition(132.0000, 35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_name)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.6286)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3429)
layout:setPercentHeight(0.5143)
layout:setSize({width = 72.0000, height = 36.0000})
layout:setLeftMargin(96.0000)
layout:setRightMargin(42.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
btn_share:addChild(btn_name)

--Create img_wx
local img_wx = ccui.ImageView:create()
img_wx:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/lotto.plist")
img_wx:loadTexture("hall/lotto/img_wx.png",1)
img_wx:setLayoutComponentEnabled(true)
img_wx:setName("img_wx")
img_wx:setTag(695)
img_wx:setCascadeColorEnabled(true)
img_wx:setCascadeOpacityEnabled(true)
img_wx:setPosition(62.0000, 34.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_wx)
layout:setPositionPercentX(0.2952)
layout:setPositionPercentY(0.4857)
layout:setPercentWidth(0.2095)
layout:setPercentHeight(0.5286)
layout:setSize({width = 44.0000, height = 37.0000})
layout:setLeftMargin(40.0000)
layout:setRightMargin(126.0000)
layout:setTopMargin(17.5000)
layout:setBottomMargin(15.5000)
btn_share:addChild(img_wx)

--Create btn_more
local btn_more = ccui.Layout:create()
btn_more:ignoreContentAdaptWithSize(false)
btn_more:setClippingEnabled(false)
btn_more:setTouchEnabled(true);
btn_more:setLayoutComponentEnabled(true)
btn_more:setName("btn_more")
btn_more:setTag(696)
btn_more:setCascadeColorEnabled(true)
btn_more:setCascadeOpacityEnabled(true)
btn_more:setAnchorPoint(0.5000, 0.5000)
btn_more:setPosition(140.0000, -186.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_more)
layout:setSize({width = 210.0000, height = 70.0000})
layout:setLeftMargin(35.0000)
layout:setRightMargin(-245.0000)
layout:setTopMargin(151.0000)
layout:setBottomMargin(-221.0000)
Node:addChild(btn_more)

--Create btn_bg
local btn_bg = ccui.ImageView:create()
btn_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_bg:loadTexture("hall/common/new_btn_noangle.png",1)
btn_bg:setScale9Enabled(true)
btn_bg:setCapInsets({x = 8, y = 8, width = 2, height = 2})
btn_bg:setLayoutComponentEnabled(true)
btn_bg:setName("btn_bg")
btn_bg:setTag(1480)
btn_bg:setCascadeColorEnabled(true)
btn_bg:setCascadeOpacityEnabled(true)
btn_bg:setPosition(105.0000, 35.0000)
btn_bg:setColor({r = 16, g = 116, b = 233})
layout = ccui.LayoutComponent:bindLayoutComponent(btn_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 210.0000, height = 70.0000})
btn_more:addChild(btn_bg)

--Create btn_name
local btn_name = ccui.Text:create()
btn_name:ignoreContentAdaptWithSize(true)
btn_name:setTextAreaSize({width = 0, height = 0})
btn_name:setFontSize(36)
btn_name:setString([[领取]])
btn_name:setLayoutComponentEnabled(true)
btn_name:setName("btn_name")
btn_name:setTag(697)
btn_name:setCascadeColorEnabled(true)
btn_name:setCascadeOpacityEnabled(true)
btn_name:setPosition(105.0000, 35.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_name)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3429)
layout:setPercentHeight(0.5143)
layout:setSize({width = 72.0000, height = 36.0000})
layout:setLeftMargin(69.0000)
layout:setRightMargin(69.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
btn_more:addChild(btn_name)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

