--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel_bg
local panel_bg = ccui.Layout:create()
panel_bg:ignoreContentAdaptWithSize(false)
panel_bg:setClippingEnabled(false)
panel_bg:setBackGroundColorOpacity(102)
panel_bg:setTouchEnabled(true);
panel_bg:setLayoutComponentEnabled(true)
panel_bg:setName("panel_bg")
panel_bg:setTag(508)
panel_bg:setCascadeColorEnabled(true)
panel_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_bg)
layout:setSize({width = 816.0000, height = 634.0000})
layout:setRightMargin(-816.0000)
layout:setTopMargin(-634.0000)
Node:addChild(panel_bg)

--Create img_download
local img_download = ccui.ImageView:create()
img_download:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_download:loadTexture("hall/common/pic_Loading.png",1)
img_download:setFlippedX(true)
img_download:setLayoutComponentEnabled(true)
img_download:setName("img_download")
img_download:setTag(27)
img_download:setCascadeColorEnabled(true)
img_download:setCascadeOpacityEnabled(true)
img_download:setVisible(false)
img_download:setPosition(408.0000, 390.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_download)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6151)
layout:setPercentWidth(0.1324)
layout:setPercentHeight(0.1703)
layout:setSize({width = 108.0000, height = 108.0000})
layout:setLeftMargin(354.0000)
layout:setRightMargin(354.0000)
layout:setTopMargin(190.0000)
layout:setBottomMargin(336.0000)
panel_bg:addChild(img_download)

--Create txt_tips
local txt_tips = ccui.Text:create()
txt_tips:ignoreContentAdaptWithSize(true)
txt_tips:setTextAreaSize({width = 0, height = 0})
txt_tips:setFontName("")
txt_tips:setFontSize(28)
txt_tips:setString([[正在研发中，敬请期待！]])
txt_tips:setLayoutComponentEnabled(true)
txt_tips:setName("txt_tips")
txt_tips:setTag(52)
txt_tips:setCascadeColorEnabled(true)
txt_tips:setCascadeOpacityEnabled(true)
txt_tips:setVisible(false)
txt_tips:setPosition(408.0000, 320.0000)
txt_tips:setTextColor({r = 51, g = 51, b = 51})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_tips)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5047)
layout:setPercentWidth(0.3775)
layout:setPercentHeight(0.0442)
layout:setSize({width = 308.0000, height = 28.0000})
layout:setLeftMargin(254.0000)
layout:setRightMargin(254.0000)
layout:setTopMargin(300.0000)
layout:setBottomMargin(306.0000)
panel_bg:addChild(txt_tips)

--Create img_line
local img_line = ccui.ImageView:create()
img_line:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_line:loadTexture("hall/common/new_line.png",1)
img_line:setScale9Enabled(true)
img_line:setCapInsets({x = 1, y = 0, width = 2, height = 1})
img_line:setLayoutComponentEnabled(true)
img_line:setName("img_line")
img_line:setTag(434)
img_line:setCascadeColorEnabled(true)
img_line:setCascadeOpacityEnabled(true)
img_line:setAnchorPoint(0.0000, 0.5000)
img_line:setPosition(0.0000, 99.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_line)
layout:setSize({width = 816.0000, height = 1.0000})
layout:setRightMargin(-816.0000)
layout:setTopMargin(-99.5000)
layout:setBottomMargin(98.5000)
Node:addChild(img_line)

--Create panel_update
local panel_update = ccui.Layout:create()
panel_update:ignoreContentAdaptWithSize(false)
panel_update:setClippingEnabled(false)
panel_update:setBackGroundColorOpacity(102)
panel_update:setTouchEnabled(true);
panel_update:setLayoutComponentEnabled(true)
panel_update:setName("panel_update")
panel_update:setTag(509)
panel_update:setCascadeColorEnabled(true)
panel_update:setCascadeOpacityEnabled(true)
panel_update:setVisible(false)
panel_update:setAnchorPoint(0.5000, 0.5000)
panel_update:setPosition(676.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_update)
layout:setSize({width = 240.0000, height = 60.0000})
layout:setLeftMargin(556.0000)
layout:setRightMargin(-796.0000)
layout:setTopMargin(-79.0000)
layout:setBottomMargin(19.0000)
Node:addChild(panel_update)

--Create btn_update
local btn_update = ccui.Button:create()
btn_update:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_update:loadTextureNormal("hall/common/new_btn_noangle.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_update:loadTexturePressed("hall/common/new_btn_noangle.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_update:loadTextureDisabled("hall/common/new_btn_noangle.png",1)
btn_update:setTitleFontSize(14)
btn_update:setTitleColor({r = 65, g = 65, b = 70})
btn_update:setScale9Enabled(true)
btn_update:setCapInsets({x = 8, y = 8, width = 2, height = 2})
btn_update:setLayoutComponentEnabled(true)
btn_update:setName("btn_update")
btn_update:setTag(53)
btn_update:setCascadeColorEnabled(true)
btn_update:setCascadeOpacityEnabled(true)
btn_update:setPosition(120.0000, 30.0000)
btn_update:setColor({r = 38, g = 155, b = 88})
layout = ccui.LayoutComponent:bindLayoutComponent(btn_update)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 240.0000, height = 60.0000})
panel_update:addChild(btn_update)

--Create txt_btnTitle
local txt_btnTitle = ccui.Text:create()
txt_btnTitle:ignoreContentAdaptWithSize(true)
txt_btnTitle:setTextAreaSize({width = 0, height = 0})
txt_btnTitle:setFontName("")
txt_btnTitle:setFontSize(32)
txt_btnTitle:setString([[更 新]])
txt_btnTitle:setLayoutComponentEnabled(true)
txt_btnTitle:setName("txt_btnTitle")
txt_btnTitle:setTag(54)
txt_btnTitle:setCascadeColorEnabled(true)
txt_btnTitle:setCascadeOpacityEnabled(true)
txt_btnTitle:setPosition(120.0000, 29.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_btnTitle)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4833)
layout:setPercentWidth(0.3333)
layout:setPercentHeight(0.5500)
layout:setSize({width = 80.0000, height = 33.0000})
layout:setLeftMargin(80.0000)
layout:setRightMargin(80.0000)
layout:setTopMargin(14.5000)
layout:setBottomMargin(12.5000)
panel_update:addChild(txt_btnTitle)

--Create panel_create
local panel_create = ccui.Layout:create()
panel_create:ignoreContentAdaptWithSize(false)
panel_create:setClippingEnabled(false)
panel_create:setBackGroundColorOpacity(102)
panel_create:setTouchEnabled(true);
panel_create:setLayoutComponentEnabled(true)
panel_create:setName("panel_create")
panel_create:setTag(510)
panel_create:setCascadeColorEnabled(true)
panel_create:setCascadeOpacityEnabled(true)
panel_create:setAnchorPoint(0.5000, 0.5000)
panel_create:setPosition(676.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_create)
layout:setSize({width = 240.0000, height = 60.0000})
layout:setLeftMargin(556.0000)
layout:setRightMargin(-796.0000)
layout:setTopMargin(-79.0000)
layout:setBottomMargin(19.0000)
Node:addChild(panel_create)

--Create btn_create
local btn_create = ccui.Button:create()
btn_create:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_create:loadTextureNormal("hall/common/new_btn_noangle.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_create:loadTexturePressed("hall/common/new_btn_noangle.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_create:loadTextureDisabled("hall/common/new_btn_noangle.png",1)
btn_create:setTitleFontSize(14)
btn_create:setTitleColor({r = 65, g = 65, b = 70})
btn_create:setScale9Enabled(true)
btn_create:setCapInsets({x = 8, y = 8, width = 2, height = 2})
btn_create:setLayoutComponentEnabled(true)
btn_create:setName("btn_create")
btn_create:setTag(358)
btn_create:setCascadeColorEnabled(true)
btn_create:setCascadeOpacityEnabled(true)
btn_create:setPosition(120.0000, 30.0000)
btn_create:setColor({r = 38, g = 155, b = 88})
layout = ccui.LayoutComponent:bindLayoutComponent(btn_create)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 240.0000, height = 60.0000})
panel_create:addChild(btn_create)

--Create txt_btnTitle
local txt_btnTitle = ccui.Text:create()
txt_btnTitle:ignoreContentAdaptWithSize(true)
txt_btnTitle:setTextAreaSize({width = 0, height = 0})
txt_btnTitle:setFontName("")
txt_btnTitle:setFontSize(32)
txt_btnTitle:setString([[创建房间]])
txt_btnTitle:setLayoutComponentEnabled(true)
txt_btnTitle:setName("txt_btnTitle")
txt_btnTitle:setTag(359)
txt_btnTitle:setCascadeColorEnabled(true)
txt_btnTitle:setCascadeOpacityEnabled(true)
txt_btnTitle:setPosition(120.0000, 29.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_btnTitle)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4833)
layout:setPercentWidth(0.5333)
layout:setPercentHeight(0.5500)
layout:setSize({width = 128.0000, height = 33.0000})
layout:setLeftMargin(56.0000)
layout:setRightMargin(56.0000)
layout:setTopMargin(14.5000)
layout:setBottomMargin(12.5000)
panel_create:addChild(txt_btnTitle)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

