--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create tab_btn
local tab_btn = ccui.Layout:create()
tab_btn:ignoreContentAdaptWithSize(false)
tab_btn:setClippingEnabled(false)
tab_btn:setBackGroundColorOpacity(102)
tab_btn:setTouchEnabled(true);
tab_btn:setLayoutComponentEnabled(true)
tab_btn:setName("tab_btn")
tab_btn:setTag(56)
tab_btn:setCascadeColorEnabled(true)
tab_btn:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(tab_btn)
layout:setSize({width = 274.0000, height = 92.0000})
layout:setRightMargin(-274.0000)
layout:setTopMargin(-92.0000)
Node:addChild(tab_btn)

--Create img_sep
local img_sep = ccui.ImageView:create()
img_sep:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_sep:loadTexture("hall/common/new_virtual_line.png",1)
img_sep:setLayoutComponentEnabled(true)
img_sep:setName("img_sep")
img_sep:setTag(57)
img_sep:setCascadeColorEnabled(true)
img_sep:setCascadeOpacityEnabled(true)
img_sep:setAnchorPoint(0.5000, 0.0000)
img_sep:setPosition(137.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_sep)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0217)
layout:setSize({width = 274.0000, height = 2.0000})
layout:setTopMargin(90.0000)
tab_btn:addChild(img_sep)

--Create img_sel
local img_sel = ccui.ImageView:create()
img_sel:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_sel:loadTexture("hall/common/new_pop_select_bg.png",1)
img_sel:setScale9Enabled(true)
img_sel:setCapInsets({x = 104, y = 30, width = 66, height = 38})
img_sel:setLayoutComponentEnabled(true)
img_sel:setName("img_sel")
img_sel:setTag(58)
img_sel:setCascadeColorEnabled(true)
img_sel:setCascadeOpacityEnabled(true)
img_sel:setVisible(false)
img_sel:setAnchorPoint(0.5000, 1.0000)
img_sel:setPosition(137.0000, 92.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_sel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 274.0000, height = 92.0000})
tab_btn:addChild(img_sel)

--Create img_icon
local img_icon = ccui.ImageView:create()
img_icon:ignoreContentAdaptWithSize(false)
img_icon:loadTexture("weile/icon_default.png",0)
img_icon:setLayoutComponentEnabled(true)
img_icon:setName("img_icon")
img_icon:setTag(59)
img_icon:setCascadeColorEnabled(true)
img_icon:setCascadeOpacityEnabled(true)
img_icon:setPosition(42.0000, 46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_icon)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1533)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2190)
layout:setPercentHeight(0.6522)
layout:setSize({width = 60.0000, height = 60.0000})
layout:setLeftMargin(12.0000)
layout:setRightMargin(202.0000)
layout:setTopMargin(16.0000)
layout:setBottomMargin(16.0000)
tab_btn:addChild(img_icon)

--Create txt_game
local txt_game = ccui.Text:create()
txt_game:ignoreContentAdaptWithSize(true)
txt_game:setTextAreaSize({width = 0, height = 0})
txt_game:setFontName("")
txt_game:setFontSize(32)
txt_game:setString([[长春麻将]])
txt_game:setLayoutComponentEnabled(true)
txt_game:setName("txt_game")
txt_game:setTag(60)
txt_game:setCascadeColorEnabled(true)
txt_game:setCascadeOpacityEnabled(true)
txt_game:setAnchorPoint(0.0000, 0.5000)
txt_game:setPosition(80.0000, 46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_game)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2920)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4672)
layout:setPercentHeight(0.3587)
layout:setSize({width = 128.0000, height = 33.0000})
layout:setLeftMargin(80.0000)
layout:setRightMargin(66.0000)
layout:setTopMargin(29.5000)
layout:setBottomMargin(29.5000)
tab_btn:addChild(txt_game)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

