--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("common/bg_box_s.png",0)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 33, y = 33, width = 34, height = 34})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(64)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 740.0000, height = 420.0000})
layout:setLeftMargin(-370.0000)
layout:setRightMargin(-370.0000)
layout:setTopMargin(-210.0000)
layout:setBottomMargin(-210.0000)
Node:addChild(img_bg)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontSize(38)
txt_title:setString([[温馨提示]])
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(66)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setAnchorPoint(0.5036, 0.5121)
txt_title:setPosition(370.0000, 380.0000)
txt_title:setTextColor({r = 112, g = 41, b = 9})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9048)
layout:setPercentWidth(0.2068)
layout:setPercentHeight(0.1048)
layout:setSize({width = 153.0000, height = 44.0000})
layout:setLeftMargin(292.9492)
layout:setRightMargin(294.0508)
layout:setTopMargin(18.5324)
layout:setBottomMargin(357.4676)
img_bg:addChild(txt_title)

--Create img_line
local img_line = ccui.ImageView:create()
img_line:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_line:loadTexture("hall/common/line.png",1)
img_line:setLayoutComponentEnabled(true)
img_line:setName("img_line")
img_line:setTag(68)
img_line:setCascadeColorEnabled(true)
img_line:setCascadeOpacityEnabled(true)
img_line:setPosition(370.0000, 350.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_line)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8333)
layout:setPercentWidth(0.9784)
layout:setPercentHeight(0.0048)
layout:setSize({width = 724.0000, height = 2.0000})
layout:setLeftMargin(8.0000)
layout:setRightMargin(8.0000)
layout:setTopMargin(69.0000)
layout:setBottomMargin(349.0000)
img_bg:addChild(img_line)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_close:loadTextureNormal("hall/common/btn_x.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_close:loadTexturePressed("hall/common/btn_x.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_close:loadTextureDisabled("hall/common/btn_x.png",1)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 2, height = 10})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(69)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(700.0000, 382.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.9459)
layout:setPositionPercentY(0.9095)
layout:setPercentWidth(0.0432)
layout:setPercentHeight(0.0762)
layout:setSize({width = 32.0000, height = 32.0000})
layout:setLeftMargin(684.0000)
layout:setRightMargin(24.0000)
layout:setTopMargin(22.0000)
layout:setBottomMargin(366.0000)
img_bg:addChild(btn_close)

--Create txt_content
local txt_content = ccui.Text:create()
txt_content:ignoreContentAdaptWithSize(true)
txt_content:setTextAreaSize({width = 0, height = 0})
txt_content:setFontName("")
txt_content:setFontSize(30)
txt_content:setString([[当前房间是GPS场，是否开启GPS加入该
房间。（不开启无法加入该房间）]])
txt_content:setLayoutComponentEnabled(true)
txt_content:setName("txt_content")
txt_content:setTag(70)
txt_content:setCascadeColorEnabled(true)
txt_content:setCascadeOpacityEnabled(true)
txt_content:setAnchorPoint(0.5036, 0.5000)
txt_content:setPosition(370.0000, 300.0000)
txt_content:setTextColor({r = 112, g = 41, b = 9})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_content)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7143)
layout:setPercentWidth(0.6892)
layout:setPercentHeight(0.1429)
layout:setSize({width = 510.0000, height = 60.0000})
layout:setLeftMargin(113.1640)
layout:setRightMargin(116.8360)
layout:setTopMargin(90.0000)
layout:setBottomMargin(270.0000)
img_bg:addChild(txt_content)

--Create img_gps
local img_gps = ccui.ImageView:create()
img_gps:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_gps:loadTexture("hall/common/btn_gps.png",1)
img_gps:setLayoutComponentEnabled(true)
img_gps:setName("img_gps")
img_gps:setTag(71)
img_gps:setCascadeColorEnabled(true)
img_gps:setCascadeOpacityEnabled(true)
img_gps:setPosition(370.0000, 180.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_gps)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4286)
layout:setPercentWidth(0.1838)
layout:setPercentHeight(0.2571)
layout:setSize({width = 136.0000, height = 108.0000})
layout:setLeftMargin(302.0000)
layout:setRightMargin(302.0000)
layout:setTopMargin(186.0000)
layout:setBottomMargin(126.0000)
img_bg:addChild(img_gps)

--Create btn_open
local btn_open = ccui.Button:create()
btn_open:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_open:loadTextureNormal("hall/common/btn_green.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_open:loadTexturePressed("hall/common/btn_green.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_open:loadTextureDisabled("hall/common/btn_green.png",1)
btn_open:setTitleFontSize(14)
btn_open:setTitleColor({r = 65, g = 65, b = 70})
btn_open:setScale9Enabled(true)
btn_open:setCapInsets({x = 9, y = 9, width = 1, height = 1})
btn_open:setLayoutComponentEnabled(true)
btn_open:setName("btn_open")
btn_open:setTag(72)
btn_open:setCascadeColorEnabled(true)
btn_open:setCascadeOpacityEnabled(true)
btn_open:setPosition(370.0000, 75.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_open)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1786)
layout:setPercentWidth(0.3108)
layout:setPercentHeight(0.1667)
layout:setSize({width = 230.0000, height = 70.0000})
layout:setLeftMargin(255.0000)
layout:setRightMargin(255.0000)
layout:setTopMargin(310.0000)
layout:setBottomMargin(40.0000)
img_bg:addChild(btn_open)

--Create txt_btn_title
local txt_btn_title = ccui.Text:create()
txt_btn_title:ignoreContentAdaptWithSize(true)
txt_btn_title:setTextAreaSize({width = 0, height = 0})
txt_btn_title:setFontSize(32)
txt_btn_title:setString([[前往开启]])
txt_btn_title:setLayoutComponentEnabled(true)
txt_btn_title:setName("txt_btn_title")
txt_btn_title:setTag(73)
txt_btn_title:setCascadeColorEnabled(true)
txt_btn_title:setCascadeOpacityEnabled(true)
txt_btn_title:setPosition(115.0000, 31.8990)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_btn_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4557)
layout:setPercentWidth(0.5652)
layout:setPercentHeight(0.5286)
layout:setSize({width = 130.0000, height = 37.0000})
layout:setLeftMargin(50.0000)
layout:setRightMargin(50.0000)
layout:setTopMargin(19.6010)
layout:setBottomMargin(13.3990)
btn_open:addChild(txt_btn_title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

