--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create detail_layout
local detail_layout = ccui.Layout:create()
detail_layout:ignoreContentAdaptWithSize(false)
detail_layout:setClippingEnabled(false)
detail_layout:setBackGroundColorOpacity(102)
detail_layout:setTouchEnabled(true);
detail_layout:setLayoutComponentEnabled(true)
detail_layout:setName("detail_layout")
detail_layout:setTag(138)
detail_layout:setCascadeColorEnabled(true)
detail_layout:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(detail_layout)
layout:setSize({width = 806.0000, height = 76.0000})
layout:setRightMargin(-806.0000)
layout:setTopMargin(-76.0000)
Node:addChild(detail_layout)

--Create title_container
local title_container = ccui.Layout:create()
title_container:ignoreContentAdaptWithSize(false)
title_container:setClippingEnabled(false)
title_container:setLayoutComponentEnabled(true)
title_container:setName("title_container")
title_container:setTag(132)
title_container:setCascadeColorEnabled(true)
title_container:setCascadeOpacityEnabled(true)
title_container:setAnchorPoint(0.0000, 1.0000)
title_container:setPosition(0.0000, 76.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(title_container)
layout:setPositionPercentY(1.0000)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 806.0000, height = 76.0000})
detail_layout:addChild(title_container)

--Create label_title
local label_title = ccui.Text:create()
label_title:ignoreContentAdaptWithSize(true)
label_title:setTextAreaSize({width = 0, height = 0})
label_title:setFontName("")
label_title:setFontSize(30)
label_title:setString([[最近更新]])
label_title:setLayoutComponentEnabled(true)
label_title:setName("label_title")
label_title:setTag(133)
label_title:setCascadeColorEnabled(true)
label_title:setCascadeOpacityEnabled(true)
label_title:setAnchorPoint(0.0000, 0.5000)
label_title:setPosition(29.9998, 39.5200)
label_title:setTextColor({r = 34, g = 34, b = 34})
layout = ccui.LayoutComponent:bindLayoutComponent(label_title)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0372)
layout:setPositionPercentY(0.5200)
layout:setPercentWidth(0.1489)
layout:setPercentHeight(0.3947)
layout:setSize({width = 120.0000, height = 30.0000})
layout:setLeftMargin(29.9998)
layout:setRightMargin(656.0002)
layout:setTopMargin(21.4800)
layout:setBottomMargin(24.5200)
title_container:addChild(label_title)

--Create btn_extend
local btn_extend = ccui.Button:create()
btn_extend:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/feedback.plist")
btn_extend:loadTextureNormal("hall/feedback/shape_xl_2.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/feedback.plist")
btn_extend:loadTexturePressed("hall/feedback/shape_xl_2.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/feedback.plist")
btn_extend:loadTextureDisabled("hall/feedback/shape_xl_2.png",1)
btn_extend:setTitleFontSize(14)
btn_extend:setTitleColor({r = 65, g = 65, b = 70})
btn_extend:setScale9Enabled(true)
btn_extend:setCapInsets({x = 15, y = 6, width = 1, height = 8})
btn_extend:setLayoutComponentEnabled(true)
btn_extend:setName("btn_extend")
btn_extend:setTag(160)
btn_extend:setCascadeColorEnabled(true)
btn_extend:setCascadeOpacityEnabled(true)
btn_extend:setPosition(736.0001, 39.5200)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_extend)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.9132)
layout:setPositionPercentY(0.5200)
layout:setPercentWidth(0.0385)
layout:setPercentHeight(0.2632)
layout:setSize({width = 31.0000, height = 20.0000})
layout:setLeftMargin(720.5001)
layout:setRightMargin(54.4999)
layout:setTopMargin(26.4800)
layout:setBottomMargin(29.5200)
title_container:addChild(btn_extend)

--Create btn_extend_layout
local btn_extend_layout = ccui.Layout:create()
btn_extend_layout:ignoreContentAdaptWithSize(false)
btn_extend_layout:setClippingEnabled(false)
btn_extend_layout:setBackGroundColorOpacity(102)
btn_extend_layout:setTouchEnabled(true);
btn_extend_layout:setLayoutComponentEnabled(true)
btn_extend_layout:setName("btn_extend_layout")
btn_extend_layout:setTag(65)
btn_extend_layout:setCascadeColorEnabled(true)
btn_extend_layout:setCascadeOpacityEnabled(true)
btn_extend_layout:setAnchorPoint(0.5000, 0.5000)
btn_extend_layout:setPosition(14.9989, 9.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_extend_layout)
layout:setPositionPercentX(0.4838)
layout:setPositionPercentY(0.4500)
layout:setPercentWidth(2.5806)
layout:setPercentHeight(3.0000)
layout:setSize({width = 80.0000, height = 60.0000})
layout:setLeftMargin(-25.0011)
layout:setRightMargin(-23.9989)
layout:setTopMargin(-19.0000)
layout:setBottomMargin(-21.0000)
btn_extend:addChild(btn_extend_layout)

--Create detail_container
local detail_container = ccui.Layout:create()
detail_container:ignoreContentAdaptWithSize(false)
detail_container:setClippingEnabled(true)
detail_container:setBackGroundColorOpacity(102)
detail_container:setLayoutComponentEnabled(true)
detail_container:setName("detail_container")
detail_container:setTag(135)
detail_container:setCascadeColorEnabled(true)
detail_container:setCascadeOpacityEnabled(true)
detail_container:setPosition(5.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(detail_container)
layout:setPositionPercentX(0.0062)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setSize({width = 806.0000, height = 0.0000})
layout:setLeftMargin(5.0000)
layout:setRightMargin(-5.0000)
layout:setTopMargin(76.0000)
detail_layout:addChild(detail_container)

--Create detail_line
local detail_line = ccui.ImageView:create()
detail_line:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
detail_line:loadTexture("hall/common/new_line.png",1)
detail_line:setScale9Enabled(true)
detail_line:setCapInsets({x = 1, y = 0, width = 1, height = 1})
detail_line:setLayoutComponentEnabled(true)
detail_line:setName("detail_line")
detail_line:setTag(139)
detail_line:setCascadeColorEnabled(true)
detail_line:setCascadeOpacityEnabled(true)
detail_line:setAnchorPoint(0.5000, 0.0000)
detail_line:setPosition(403.0000, 1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(detail_line)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0132)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0263)
layout:setSize({width = 806.0000, height = 2.0000})
layout:setTopMargin(73.0000)
layout:setBottomMargin(1.0000)
detail_layout:addChild(detail_line)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

