--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create btn_time
local btn_time = ccui.Layout:create()
btn_time:ignoreContentAdaptWithSize(false)
btn_time:setClippingEnabled(false)
btn_time:setBackGroundImageCapInsets({x = -1, y = -1, width = 2, height = 2})
btn_time:setBackGroundImageScale9Enabled(true)
btn_time:setTouchEnabled(true);
btn_time:setLayoutComponentEnabled(true)
btn_time:setName("btn_time")
btn_time:setTag(106)
btn_time:setCascadeColorEnabled(true)
btn_time:setCascadeOpacityEnabled(true)
btn_time:setAnchorPoint(0.0000, 0.5000)
btn_time:setPosition(-90.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_time)
layout:setSize({width = 180.0000, height = 60.5000})
layout:setLeftMargin(-90.0000)
layout:setRightMargin(-90.0000)
layout:setTopMargin(-30.2500)
layout:setBottomMargin(-30.2500)
Node:addChild(btn_time)

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/arena.plist")
img_bg:loadTexture("hall/arena/bg_btn_paihang.png",1)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 4, y = 4, width = 4, height = 5})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(195)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setAnchorPoint(0.0000, 0.5000)
img_bg:setPosition(0.0001, 30.2500)
img_bg:setColor({r = 209, g = 238, b = 255})
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 180.0000, height = 60.5000})
layout:setLeftMargin(0.0001)
layout:setRightMargin(-0.0001)
btn_time:addChild(img_bg)

--Create img_tag
local img_tag = ccui.ImageView:create()
img_tag:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/arena.plist")
img_tag:loadTexture("hall/arena/icon__paihang_xz.png",1)
img_tag:setLayoutComponentEnabled(true)
img_tag:setName("img_tag")
img_tag:setTag(104)
img_tag:setCascadeColorEnabled(true)
img_tag:setCascadeOpacityEnabled(true)
img_tag:setAnchorPoint(0.5000, 0.0000)
img_tag:setPosition(90.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_tag)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(0.1111)
layout:setPercentHeight(0.1983)
layout:setSize({width = 20.0000, height = 12.0000})
layout:setLeftMargin(80.0000)
layout:setRightMargin(80.0000)
layout:setTopMargin(48.5000)
btn_time:addChild(img_tag)

--Create txt_time
local txt_time = ccui.Text:create()
txt_time:ignoreContentAdaptWithSize(true)
txt_time:setTextAreaSize({width = 0, height = 0})
txt_time:setFontSize(28)
txt_time:setString([[第一期]])
txt_time:setLayoutComponentEnabled(true)
txt_time:setName("txt_time")
txt_time:setTag(109)
txt_time:setCascadeColorEnabled(true)
txt_time:setCascadeOpacityEnabled(true)
txt_time:setPosition(47.1879, 30.2500)
txt_time:setTextColor({r = 58, g = 111, b = 192})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_time)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2622)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4667)
layout:setPercentHeight(0.4628)
layout:setSize({width = 84.0000, height = 28.0000})
layout:setLeftMargin(5.1879)
layout:setRightMargin(90.8121)
layout:setTopMargin(16.2500)
layout:setBottomMargin(16.2500)
btn_time:addChild(txt_time)

--Create txt_jxz
local txt_jxz = ccui.Text:create()
txt_jxz:ignoreContentAdaptWithSize(true)
txt_jxz:setTextAreaSize({width = 0, height = 0})
txt_jxz:setFontSize(28)
txt_jxz:setString([[进行中]])
txt_jxz:setLayoutComponentEnabled(true)
txt_jxz:setName("txt_jxz")
txt_jxz:setTag(1495)
txt_jxz:setCascadeColorEnabled(true)
txt_jxz:setCascadeOpacityEnabled(true)
txt_jxz:setVisible(false)
txt_jxz:setAnchorPoint(0.0000, 0.5000)
txt_jxz:setPosition(90.0000, 30.2500)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_jxz)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4667)
layout:setPercentHeight(0.4628)
layout:setSize({width = 84.0000, height = 28.0000})
layout:setLeftMargin(90.0000)
layout:setRightMargin(6.0000)
layout:setTopMargin(16.2500)
layout:setBottomMargin(16.2500)
btn_time:addChild(txt_jxz)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

