--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("hall/active/bonuspool/rule/bottom.png",0)
bg:setScale9Enabled(true)
bg:setCapInsets({x = 43, y = 43, width = 113, height = 91})
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(358)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(0.0001, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setSize({width = 1138.0000, height = 496.0000})
layout:setLeftMargin(-568.9999)
layout:setRightMargin(-569.0001)
layout:setTopMargin(-248.0000)
layout:setBottomMargin(-248.0000)
Node:addChild(bg)

--Create text_title
local text_title = ccui.Text:create()
text_title:ignoreContentAdaptWithSize(true)
text_title:setTextAreaSize({width = 0, height = 0})
text_title:setFontSize(40)
text_title:setString([[活动规则]])
text_title:setLayoutComponentEnabled(true)
text_title:setName("text_title")
text_title:setTag(359)
text_title:setCascadeColorEnabled(true)
text_title:setCascadeOpacityEnabled(true)
text_title:setPosition(0.0000, 179.0000)
text_title:setTextColor({r = 142, g = 30, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(text_title)
layout:setSize({width = 161.0000, height = 46.0000})
layout:setLeftMargin(-80.5000)
layout:setRightMargin(-80.5000)
layout:setTopMargin(-202.0000)
layout:setBottomMargin(156.0000)
Node:addChild(text_title)

--Create btn_close
local btn_close = ccui.Layout:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:setClippingEnabled(false)
btn_close:setBackGroundColorOpacity(102)
btn_close:setTouchEnabled(true);
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(74)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setAnchorPoint(0.5000, 0.5000)
btn_close:setPosition(490.0000, 192.0000)
btn_close:setColor({r = 142, g = 30, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setSize({width = 60.0000, height = 60.0000})
layout:setLeftMargin(460.0000)
layout:setRightMargin(-520.0000)
layout:setTopMargin(-222.0000)
layout:setBottomMargin(162.0000)
Node:addChild(btn_close)

--Create Image_4
local Image_4 = ccui.ImageView:create()
Image_4:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
Image_4:loadTexture("hall/common/new_btn_close.png",1)
Image_4:setLayoutComponentEnabled(true)
Image_4:setName("Image_4")
Image_4:setTag(87)
Image_4:setCascadeColorEnabled(true)
Image_4:setCascadeOpacityEnabled(true)
Image_4:setPosition(30.0000, 30.0000)
Image_4:setColor({r = 142, g = 30, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Image_4)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.4333)
layout:setPercentHeight(0.4333)
layout:setSize({width = 26.0000, height = 26.0000})
layout:setLeftMargin(17.0000)
layout:setRightMargin(17.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
btn_close:addChild(Image_4)

--Create text_info
local text_info = ccui.Text:create()
text_info:ignoreContentAdaptWithSize(false)
text_info:setFontSize(26)
text_info:setString([[]])
text_info:setLayoutComponentEnabled(true)
text_info:setName("text_info")
text_info:setTag(361)
text_info:setCascadeColorEnabled(true)
text_info:setCascadeOpacityEnabled(true)
text_info:setAnchorPoint(0.0000, 1.0000)
text_info:setPosition(-495.0000, 101.0000)
text_info:setTextColor({r = 142, g = 30, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(text_info)
layout:setSize({width = 1000.0000, height = 260.0000})
layout:setLeftMargin(-495.0000)
layout:setRightMargin(-505.0000)
layout:setTopMargin(-101.0000)
layout:setBottomMargin(-159.0000)
Node:addChild(text_info)

--Create under_line
local under_line = ccui.ImageView:create()
under_line:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/bonuspool.plist")
under_line:loadTexture("hall/active/bonuspool/rule/underLine.png",1)
under_line:setScale9Enabled(true)
under_line:setCapInsets({x = 19, y = 0, width = 20, height = 2})
under_line:setLayoutComponentEnabled(true)
under_line:setName("under_line")
under_line:setTag(120)
under_line:setCascadeColorEnabled(true)
under_line:setCascadeOpacityEnabled(true)
under_line:setPosition(0.0000, 132.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(under_line)
layout:setSize({width = 950.0000, height = 2.0000})
layout:setLeftMargin(-475.0000)
layout:setRightMargin(-475.0000)
layout:setTopMargin(-133.0000)
layout:setBottomMargin(131.0000)
Node:addChild(under_line)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

