--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel_bg
local panel_bg = ccui.Layout:create()
panel_bg:ignoreContentAdaptWithSize(false)
panel_bg:setClippingEnabled(false)
panel_bg:setBackGroundImageCapInsets({x = -19, y = -18, width = 42, height = 40})
panel_bg:setBackGroundColorOpacity(229)
panel_bg:setBackGroundImageScale9Enabled(true)
panel_bg:setTouchEnabled(true);
panel_bg:setLayoutComponentEnabled(true)
panel_bg:setName("panel_bg")
panel_bg:setTag(21)
panel_bg:setCascadeColorEnabled(true)
panel_bg:setCascadeOpacityEnabled(true)
panel_bg:setAnchorPoint(0.5000, 0.5000)
panel_bg:setOpacity(229)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_bg)
layout:setSize({width = 770.0000, height = 432.0000})
layout:setLeftMargin(-385.0000)
layout:setRightMargin(-385.0000)
layout:setTopMargin(-216.0000)
layout:setBottomMargin(-216.0000)
Node:addChild(panel_bg)

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(true)
Panel_1:setBackGroundImageCapInsets({x = -5, y = -5, width = 10, height = 10})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setBackGroundImageScale9Enabled(true)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(2620)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 770.0000, height = 432.0000})
panel_bg:addChild(Panel_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
Image_1:loadTexture("hall/common/new_pop_bg_2.png",1)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 11, y = 69, width = 3, height = 4})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(399)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(385.0000, 216.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0117)
layout:setPercentHeight(1.0208)
layout:setSize({width = 779.0000, height = 441.0000})
layout:setLeftMargin(-4.5000)
layout:setRightMargin(-4.5000)
layout:setTopMargin(-4.5000)
layout:setBottomMargin(-4.5000)
Panel_1:addChild(Image_1)

--Create btn_album
local btn_album = ccui.Layout:create()
btn_album:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_album:setBackGroundImage("hall/common/btn.png",1)
btn_album:setClippingEnabled(false)
btn_album:setBackGroundImageCapInsets({x = 9, y = 9, width = 1, height = 1})
btn_album:setBackGroundColorOpacity(102)
btn_album:setBackGroundImageScale9Enabled(true)
btn_album:setTouchEnabled(true);
btn_album:setLayoutComponentEnabled(true)
btn_album:setName("btn_album")
btn_album:setTag(434)
btn_album:setCascadeColorEnabled(true)
btn_album:setCascadeOpacityEnabled(true)
btn_album:setAnchorPoint(0.5000, 0.5000)
btn_album:setPosition(539.0000, 200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_album)
layout:setPositionPercentX(0.7000)
layout:setPositionPercentY(0.4630)
layout:setPercentWidth(0.2701)
layout:setPercentHeight(0.4815)
layout:setSize({width = 208.0000, height = 208.0000})
layout:setLeftMargin(435.0000)
layout:setRightMargin(127.0000)
layout:setTopMargin(128.0000)
layout:setBottomMargin(96.0000)
Panel_1:addChild(btn_album)

--Create txt
local txt = ccui.Text:create()
txt:ignoreContentAdaptWithSize(true)
txt:setTextAreaSize({width = 0, height = 0})
txt:setFontName("")
txt:setFontSize(40)
txt:setString([[相册]])
txt:setLayoutComponentEnabled(true)
txt:setName("txt")
txt:setTag(16)
txt:setCascadeColorEnabled(true)
txt:setCascadeOpacityEnabled(true)
txt:setPosition(104.0000, -40.0000)
txt:setTextColor({r = 51, g = 51, b = 51})
layout = ccui.LayoutComponent:bindLayoutComponent(txt)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-0.1923)
layout:setPercentWidth(0.3846)
layout:setPercentHeight(0.1923)
layout:setSize({width = 80.0000, height = 40.0000})
layout:setLeftMargin(64.0000)
layout:setRightMargin(64.0000)
layout:setTopMargin(228.0000)
layout:setBottomMargin(-60.0000)
btn_album:addChild(txt)

--Create img
local img = ccui.ImageView:create()
img:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/person_info.plist")
img:loadTexture("hall/person_info/btn_photo.png",1)
img:setLayoutComponentEnabled(true)
img:setName("img")
img:setTag(17)
img:setCascadeColorEnabled(true)
img:setCascadeOpacityEnabled(true)
img:setPosition(104.0000, 104.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5096)
layout:setPercentHeight(0.4327)
layout:setSize({width = 106.0000, height = 90.0000})
layout:setLeftMargin(51.0000)
layout:setRightMargin(51.0000)
layout:setTopMargin(59.0000)
layout:setBottomMargin(59.0000)
btn_album:addChild(img)

--Create btn_photograph
local btn_photograph = ccui.Layout:create()
btn_photograph:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_photograph:setBackGroundImage("hall/common/btn.png",1)
btn_photograph:setClippingEnabled(false)
btn_photograph:setBackGroundImageCapInsets({x = 9, y = 9, width = 1, height = 1})
btn_photograph:setBackGroundColorOpacity(102)
btn_photograph:setBackGroundImageScale9Enabled(true)
btn_photograph:setTouchEnabled(true);
btn_photograph:setLayoutComponentEnabled(true)
btn_photograph:setName("btn_photograph")
btn_photograph:setTag(437)
btn_photograph:setCascadeColorEnabled(true)
btn_photograph:setCascadeOpacityEnabled(true)
btn_photograph:setAnchorPoint(0.5000, 0.5000)
btn_photograph:setPosition(231.0000, 200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_photograph)
layout:setPositionPercentX(0.3000)
layout:setPositionPercentY(0.4630)
layout:setPercentWidth(0.2701)
layout:setPercentHeight(0.4815)
layout:setSize({width = 208.0000, height = 208.0000})
layout:setLeftMargin(127.0000)
layout:setRightMargin(435.0000)
layout:setTopMargin(128.0000)
layout:setBottomMargin(96.0000)
Panel_1:addChild(btn_photograph)

--Create txt
local txt = ccui.Text:create()
txt:ignoreContentAdaptWithSize(true)
txt:setTextAreaSize({width = 0, height = 0})
txt:setFontName("")
txt:setFontSize(40)
txt:setString([[拍照]])
txt:setLayoutComponentEnabled(true)
txt:setName("txt")
txt:setTag(14)
txt:setCascadeColorEnabled(true)
txt:setCascadeOpacityEnabled(true)
txt:setPosition(104.0000, -40.0000)
txt:setTextColor({r = 51, g = 51, b = 51})
layout = ccui.LayoutComponent:bindLayoutComponent(txt)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(-0.1923)
layout:setPercentWidth(0.3846)
layout:setPercentHeight(0.1923)
layout:setSize({width = 80.0000, height = 40.0000})
layout:setLeftMargin(64.0000)
layout:setRightMargin(64.0000)
layout:setTopMargin(228.0000)
layout:setBottomMargin(-60.0000)
btn_photograph:addChild(txt)

--Create img
local img = ccui.ImageView:create()
img:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/person_info.plist")
img:loadTexture("hall/person_info/btn_camera.png",1)
img:setLayoutComponentEnabled(true)
img:setName("img")
img:setTag(13)
img:setCascadeColorEnabled(true)
img:setCascadeOpacityEnabled(true)
img:setPosition(104.0000, 104.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5096)
layout:setPercentHeight(0.4327)
layout:setSize({width = 106.0000, height = 90.0000})
layout:setLeftMargin(51.0000)
layout:setRightMargin(51.0000)
layout:setTopMargin(59.0000)
layout:setBottomMargin(59.0000)
btn_photograph:addChild(img)

--Create img_bg
local img_bg = ccui.Layout:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:setClippingEnabled(false)
img_bg:setBackGroundColorOpacity(102)
img_bg:setTouchEnabled(true);
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(2131)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setAnchorPoint(0.0000, 1.0000)
img_bg:setPosition(0.0000, 436.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentY(1.0093)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1551)
layout:setSize({width = 770.0000, height = 67.0000})
layout:setTopMargin(-4.0000)
layout:setBottomMargin(369.0000)
panel_bg:addChild(img_bg)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontName("")
txt_title:setFontSize(28)
txt_title:setString([[修改头像]])
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(8)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setAnchorPoint(0.0000, 0.5000)
txt_title:setPosition(24.0000, 33.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setPositionPercentX(0.0312)
layout:setPositionPercentY(0.4925)
layout:setPercentWidth(0.1455)
layout:setPercentHeight(0.4179)
layout:setSize({width = 112.0000, height = 28.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(634.0000)
layout:setTopMargin(20.0000)
layout:setBottomMargin(19.0000)
img_bg:addChild(txt_title)

--Create Panel_close
local Panel_close = ccui.Layout:create()
Panel_close:ignoreContentAdaptWithSize(false)
Panel_close:setClippingEnabled(false)
Panel_close:setBackGroundColorOpacity(102)
Panel_close:setTouchEnabled(true);
Panel_close:setLayoutComponentEnabled(true)
Panel_close:setName("Panel_close")
Panel_close:setTag(1335)
Panel_close:setCascadeColorEnabled(true)
Panel_close:setCascadeOpacityEnabled(true)
Panel_close:setAnchorPoint(0.5000, 0.5000)
Panel_close:setPosition(741.0000, 33.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_close)
layout:setPositionPercentX(0.9623)
layout:setPositionPercentY(0.4925)
layout:setPercentWidth(0.0974)
layout:setPercentHeight(1.1194)
layout:setSize({width = 75.0000, height = 75.0000})
layout:setLeftMargin(703.5000)
layout:setRightMargin(-8.5000)
layout:setTopMargin(-3.5000)
layout:setBottomMargin(-4.5000)
img_bg:addChild(Panel_close)

--Create Image_close
local Image_close = ccui.ImageView:create()
Image_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
Image_close:loadTexture("hall/common/new_btn_close.png",1)
Image_close:setLayoutComponentEnabled(true)
Image_close:setName("Image_close")
Image_close:setTag(1333)
Image_close:setCascadeColorEnabled(true)
Image_close:setCascadeOpacityEnabled(true)
Image_close:setPosition(37.5000, 37.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_close)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3200)
layout:setPercentHeight(0.3333)
layout:setSize({width = 24.0000, height = 25.0000})
layout:setLeftMargin(25.5000)
layout:setRightMargin(25.5000)
layout:setTopMargin(25.0000)
layout:setBottomMargin(25.0000)
Panel_close:addChild(Image_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

