--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create item_bg
local item_bg = ccui.Layout:create()
item_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/match_tv_view.plist")
item_bg:setBackGroundImage("hall/room/match/match_television/img_di.png",1)
item_bg:setClippingEnabled(false)
item_bg:setBackGroundColorOpacity(102)
item_bg:setTouchEnabled(true);
item_bg:setLayoutComponentEnabled(true)
item_bg:setName("item_bg")
item_bg:setTag(297)
item_bg:setCascadeColorEnabled(true)
item_bg:setCascadeOpacityEnabled(true)
item_bg:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(item_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 255.0000, height = 255.0000})
layout:setLeftMargin(-127.5000)
layout:setRightMargin(-127.5000)
layout:setTopMargin(-127.5000)
layout:setBottomMargin(-127.5000)
Node:addChild(item_bg)

--Create img_icon
local img_icon = ccui.ImageView:create()
img_icon:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/match_tv_view.plist")
img_icon:loadTexture("hall/room/match/match_television/img_tv.png",1)
img_icon:setLayoutComponentEnabled(true)
img_icon:setName("img_icon")
img_icon:setTag(299)
img_icon:setCascadeColorEnabled(true)
img_icon:setCascadeOpacityEnabled(true)
img_icon:setPosition(127.5000, 152.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_icon)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5961)
layout:setPercentWidth(0.4980)
layout:setPercentHeight(0.2667)
layout:setSize({width = 127.0000, height = 68.0000})
layout:setLeftMargin(64.0000)
layout:setRightMargin(64.0000)
layout:setTopMargin(69.0000)
layout:setBottomMargin(118.0000)
item_bg:addChild(img_icon)

--Create img_hot
local img_hot = ccui.ImageView:create()
img_hot:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/match_tv_view.plist")
img_hot:loadTexture("hall/room/match/match_television/img_label.png",1)
img_hot:setLayoutComponentEnabled(true)
img_hot:setName("img_hot")
img_hot:setTag(300)
img_hot:setCascadeColorEnabled(true)
img_hot:setCascadeOpacityEnabled(true)
img_hot:setPosition(222.6503, 220.4250)
layout = ccui.LayoutComponent:bindLayoutComponent(img_hot)
layout:setPositionPercentX(0.8731)
layout:setPositionPercentY(0.8644)
layout:setPercentWidth(0.1412)
layout:setPercentHeight(0.1882)
layout:setSize({width = 36.0000, height = 48.0000})
layout:setLeftMargin(204.6503)
layout:setRightMargin(14.3497)
layout:setTopMargin(10.5750)
layout:setBottomMargin(196.4250)
item_bg:addChild(img_hot)

--Create txt_tv
local txt_tv = ccui.Text:create()
txt_tv:ignoreContentAdaptWithSize(true)
txt_tv:setTextAreaSize({width = 0, height = 0})
txt_tv:setFontSize(30)
txt_tv:setString([[辽宁公共]])
txt_tv:setLayoutComponentEnabled(true)
txt_tv:setName("txt_tv")
txt_tv:setTag(301)
txt_tv:setCascadeColorEnabled(true)
txt_tv:setCascadeOpacityEnabled(true)
txt_tv:setPosition(127.5000, 39.9724)
txt_tv:setTextColor({r = 119, g = 42, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_tv)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1568)
layout:setPercentWidth(0.4706)
layout:setPercentHeight(0.1176)
layout:setSize({width = 120.0000, height = 30.0000})
layout:setLeftMargin(67.5000)
layout:setRightMargin(67.5000)
layout:setTopMargin(200.0276)
layout:setBottomMargin(24.9724)
item_bg:addChild(txt_tv)

--Create img_di
local img_di = ccui.ImageView:create()
img_di:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/match_tv_view.plist")
img_di:loadTexture("hall/room/match/match_television/img_di2.png",1)
img_di:setLayoutComponentEnabled(true)
img_di:setName("img_di")
img_di:setTag(1033)
img_di:setCascadeColorEnabled(true)
img_di:setCascadeOpacityEnabled(true)
img_di:setVisible(false)
img_di:setPosition(127.5000, 127.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_di)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9608)
layout:setPercentHeight(0.9608)
layout:setSize({width = 245.0000, height = 245.0000})
layout:setLeftMargin(5.0000)
layout:setRightMargin(5.0000)
layout:setTopMargin(5.0000)
layout:setBottomMargin(5.0000)
item_bg:addChild(img_di)

--Create img_unopen
local img_unopen = ccui.ImageView:create()
img_unopen:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/match_tv_view.plist")
img_unopen:loadTexture("hall/room/match/match_television/img_unopen.png",1)
img_unopen:setLayoutComponentEnabled(true)
img_unopen:setName("img_unopen")
img_unopen:setTag(1034)
img_unopen:setCascadeColorEnabled(true)
img_unopen:setCascadeOpacityEnabled(true)
img_unopen:setVisible(false)
img_unopen:setPosition(203.0054, 202.0006)
layout = ccui.LayoutComponent:bindLayoutComponent(img_unopen)
layout:setPositionPercentX(0.7961)
layout:setPositionPercentY(0.7922)
layout:setPercentWidth(0.4157)
layout:setPercentHeight(0.4118)
layout:setSize({width = 106.0000, height = 105.0000})
layout:setLeftMargin(150.0054)
layout:setRightMargin(-1.0054)
layout:setTopMargin(0.4994)
layout:setBottomMargin(149.5006)
item_bg:addChild(img_unopen)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

