--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create btn_set
local btn_set = ccui.Button:create()
btn_set:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hallMenuView2.plist")
btn_set:loadTextureNormal("hall/newhall/hall_main2/more.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hallMenuView2.plist")
btn_set:loadTexturePressed("hall/newhall/hall_main2/more.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hallMenuView2.plist")
btn_set:loadTextureDisabled("hall/newhall/hall_main2/more.png",1)
btn_set:setTitleFontSize(14)
btn_set:setTitleColor({r = 65, g = 65, b = 70})
btn_set:setScale9Enabled(true)
btn_set:setCapInsets({x = 15, y = 11, width = 30, height = 38})
btn_set:setLayoutComponentEnabled(true)
btn_set:setName("btn_set")
btn_set:setTag(148)
btn_set:setCascadeColorEnabled(true)
btn_set:setCascadeOpacityEnabled(true)
btn_set:setPosition(-50.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_set)
layout:setSize({width = 60.0000, height = 60.0000})
layout:setLeftMargin(-80.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(-30.0000)
layout:setBottomMargin(-30.0000)
Node:addChild(btn_set)

--Create nd_bean
local nd_bean=cc.Node:create()
nd_bean:setName("nd_bean")
nd_bean:setTag(162)
nd_bean:setCascadeColorEnabled(true)
nd_bean:setCascadeOpacityEnabled(true)
nd_bean:setPosition(-374.0000, 0.0008)
layout = ccui.LayoutComponent:bindLayoutComponent(nd_bean)
layout:setLeftMargin(-374.0000)
layout:setRightMargin(374.0000)
layout:setTopMargin(-0.0008)
layout:setBottomMargin(0.0008)
Node:addChild(nd_bean)

--Create bean_bg
local bean_bg = ccui.ImageView:create()
bean_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hallMenuView2.plist")
bean_bg:loadTexture("hall/newhall/hall_main2/img_doudou.png",1)
bean_bg:setScale9Enabled(true)
bean_bg:setCapInsets({x = 24, y = 14, width = 11, height = 7})
bean_bg:setTouchEnabled(true);
bean_bg:setLayoutComponentEnabled(true)
bean_bg:setName("bean_bg")
bean_bg:setTag(161)
bean_bg:setCascadeColorEnabled(true)
bean_bg:setCascadeOpacityEnabled(true)
bean_bg:setAnchorPoint(0.0000, 0.5000)
bean_bg:setPosition(17.9998, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bean_bg)
layout:setSize({width = 166.0000, height = 40.0000})
layout:setLeftMargin(17.9998)
layout:setRightMargin(-183.9998)
layout:setTopMargin(-20.0000)
layout:setBottomMargin(-20.0000)
nd_bean:addChild(bean_bg)

--Create img_bean
local img_bean = ccui.ImageView:create()
img_bean:ignoreContentAdaptWithSize(false)
img_bean:loadTexture("hall/common/prop_bean_s.png",0)
img_bean:setLayoutComponentEnabled(true)
img_bean:setName("img_bean")
img_bean:setTag(163)
img_bean:setCascadeColorEnabled(true)
img_bean:setCascadeOpacityEnabled(true)
img_bean:setAnchorPoint(0.0000, 0.5000)
img_bean:setPosition(0.0000, 4.9999)
img_bean:setScaleX(0.8300)
img_bean:setScaleY(0.8300)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bean)
layout:setSize({width = 54.0000, height = 58.0000})
layout:setRightMargin(-54.0000)
layout:setTopMargin(-33.9999)
layout:setBottomMargin(-24.0001)
nd_bean:addChild(img_bean)

--Create txt_bean
local txt_bean = ccui.Text:create()
txt_bean:ignoreContentAdaptWithSize(true)
txt_bean:setTextAreaSize({width = 0, height = 0})
txt_bean:setFontName("")
txt_bean:setFontSize(29)
txt_bean:setString([[0]])
txt_bean:setLayoutComponentEnabled(true)
txt_bean:setName("txt_bean")
txt_bean:setTag(164)
txt_bean:setCascadeColorEnabled(true)
txt_bean:setCascadeOpacityEnabled(true)
txt_bean:setAnchorPoint(0.0000, 0.5000)
txt_bean:setPosition(54.0003, 0.0000)
txt_bean:setTextColor({r = 255, g = 236, b = 90})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_bean)
layout:setSize({width = 15.0000, height = 29.0000})
layout:setLeftMargin(54.0003)
layout:setRightMargin(-69.0003)
layout:setTopMargin(-14.5000)
layout:setBottomMargin(-14.5000)
nd_bean:addChild(txt_bean)

--Create nd_diamonds
local nd_diamonds=cc.Node:create()
nd_diamonds:setName("nd_diamonds")
nd_diamonds:setTag(140)
nd_diamonds:setCascadeColorEnabled(true)
nd_diamonds:setCascadeOpacityEnabled(true)
nd_diamonds:setPosition(-597.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nd_diamonds)
layout:setLeftMargin(-597.0000)
layout:setRightMargin(597.0000)
Node:addChild(nd_diamonds)

--Create diamond_bg
local diamond_bg = ccui.ImageView:create()
diamond_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hallMenuView2.plist")
diamond_bg:loadTexture("hall/newhall/hall_main2/img_doudou.png",1)
diamond_bg:setScale9Enabled(true)
diamond_bg:setCapInsets({x = 22, y = 19, width = 11, height = 7})
diamond_bg:setTouchEnabled(true);
diamond_bg:setLayoutComponentEnabled(true)
diamond_bg:setName("diamond_bg")
diamond_bg:setTag(142)
diamond_bg:setCascadeColorEnabled(true)
diamond_bg:setCascadeOpacityEnabled(true)
diamond_bg:setAnchorPoint(0.0000, 0.5000)
diamond_bg:setPosition(17.9999, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(diamond_bg)
layout:setSize({width = 166.0000, height = 40.0000})
layout:setLeftMargin(17.9999)
layout:setRightMargin(-183.9999)
layout:setTopMargin(-20.0000)
layout:setBottomMargin(-20.0000)
nd_diamonds:addChild(diamond_bg)

--Create img_diamond
local img_diamond = ccui.ImageView:create()
img_diamond:ignoreContentAdaptWithSize(false)
img_diamond:loadTexture("hall/common/prop_diamonds.png",0)
img_diamond:setLayoutComponentEnabled(true)
img_diamond:setName("img_diamond")
img_diamond:setTag(143)
img_diamond:setCascadeColorEnabled(true)
img_diamond:setCascadeOpacityEnabled(true)
img_diamond:setAnchorPoint(0.0000, 0.5000)
img_diamond:setPosition(-0.0001, -2.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(img_diamond)
layout:setSize({width = 54.0000, height = 58.0000})
layout:setLeftMargin(-0.0001)
layout:setRightMargin(-53.9999)
layout:setTopMargin(-26.0001)
layout:setBottomMargin(-31.9999)
nd_diamonds:addChild(img_diamond)

--Create txt_diamond
local txt_diamond = ccui.Text:create()
txt_diamond:ignoreContentAdaptWithSize(true)
txt_diamond:setTextAreaSize({width = 0, height = 0})
txt_diamond:setFontName("")
txt_diamond:setFontSize(29)
txt_diamond:setString([[0]])
txt_diamond:setLayoutComponentEnabled(true)
txt_diamond:setName("txt_diamond")
txt_diamond:setTag(144)
txt_diamond:setCascadeColorEnabled(true)
txt_diamond:setCascadeOpacityEnabled(true)
txt_diamond:setAnchorPoint(0.0000, 0.5000)
txt_diamond:setPosition(62.0000, 0.0000)
txt_diamond:setTextColor({r = 255, g = 236, b = 90})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_diamond)
layout:setSize({width = 15.0000, height = 29.0000})
layout:setLeftMargin(62.0000)
layout:setRightMargin(-77.0000)
layout:setTopMargin(-14.5000)
layout:setBottomMargin(-14.5000)
nd_diamonds:addChild(txt_diamond)

--Create btn_bag
local btn_bag = ccui.Button:create()
btn_bag:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hallMenuView2.plist")
btn_bag:loadTextureNormal("hall/newhall/hall_main2/bag.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hallMenuView2.plist")
btn_bag:loadTexturePressed("hall/newhall/hall_main2/bag.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/hallMenuView2.plist")
btn_bag:loadTextureDisabled("hall/newhall/hall_main2/bag.png",1)
btn_bag:setTitleFontSize(14)
btn_bag:setTitleColor({r = 65, g = 65, b = 70})
btn_bag:setScale9Enabled(true)
btn_bag:setCapInsets({x = 15, y = 11, width = 30, height = 38})
btn_bag:setLayoutComponentEnabled(true)
btn_bag:setName("btn_bag")
btn_bag:setTag(367)
btn_bag:setCascadeColorEnabled(true)
btn_bag:setCascadeOpacityEnabled(true)
btn_bag:setPosition(-128.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_bag)
layout:setSize({width = 60.0000, height = 60.0000})
layout:setLeftMargin(-158.0000)
layout:setRightMargin(98.0000)
layout:setTopMargin(-30.0000)
layout:setBottomMargin(-30.0000)
Node:addChild(btn_bag)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

