--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel_bg
local panel_bg = ccui.Layout:create()
panel_bg:ignoreContentAdaptWithSize(false)
panel_bg:setClippingEnabled(false)
panel_bg:setBackGroundColorType(1)
panel_bg:setBackGroundColor({r = 0, g = 0, b = 0})
panel_bg:setBackGroundColorOpacity(178)
panel_bg:setTouchEnabled(true);
panel_bg:setLayoutComponentEnabled(true)
panel_bg:setName("panel_bg")
panel_bg:setTag(329)
panel_bg:setCascadeColorEnabled(true)
panel_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_bg)
layout:setSize({width = 578.0000, height = 85.0000})
layout:setRightMargin(-578.0000)
layout:setTopMargin(-85.0000)
Node:addChild(panel_bg)

--Create img_avatar
local img_avatar = ccui.ImageView:create()
img_avatar:ignoreContentAdaptWithSize(false)
img_avatar:loadTexture("Default/ImageFile.png",0)
img_avatar:setLayoutComponentEnabled(true)
img_avatar:setName("img_avatar")
img_avatar:setTag(330)
img_avatar:setCascadeColorEnabled(true)
img_avatar:setCascadeOpacityEnabled(true)
img_avatar:setPosition(42.4983, 43.5003)
img_avatar:setOpacity(0)
layout = ccui.LayoutComponent:bindLayoutComponent(img_avatar)
layout:setPositionPercentX(0.0735)
layout:setPositionPercentY(0.5118)
layout:setPercentWidth(0.1038)
layout:setPercentHeight(0.7059)
layout:setSize({width = 60.0000, height = 60.0000})
layout:setLeftMargin(12.4983)
layout:setRightMargin(505.5017)
layout:setTopMargin(11.4997)
layout:setBottomMargin(13.5003)
panel_bg:addChild(img_avatar)

--Create txt_name
local txt_name = ccui.Text:create()
txt_name:ignoreContentAdaptWithSize(true)
txt_name:setTextAreaSize({width = 0, height = 0})
txt_name:setFontSize(25)
txt_name:setString([[apple2078]])
txt_name:setLayoutComponentEnabled(true)
txt_name:setName("txt_name")
txt_name:setTag(331)
txt_name:setCascadeColorEnabled(true)
txt_name:setCascadeOpacityEnabled(true)
txt_name:setAnchorPoint(0.0000, 0.5000)
txt_name:setPosition(99.1005, 43.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_name)
layout:setPositionPercentX(0.1715)
layout:setPositionPercentY(0.5118)
layout:setPercentWidth(0.2042)
layout:setPercentHeight(0.3412)
layout:setSize({width = 118.0000, height = 29.0000})
layout:setLeftMargin(99.1005)
layout:setRightMargin(360.8995)
layout:setTopMargin(27.0000)
layout:setBottomMargin(29.0000)
panel_bg:addChild(txt_name)

--Create btn_del
local btn_del = ccui.Button:create()
btn_del:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
btn_del:loadTextureNormal("hall/login/btn_del.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
btn_del:loadTexturePressed("hall/login/btn_del.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
btn_del:loadTextureDisabled("hall/login/btn_del.png",1)
btn_del:setTitleFontSize(14)
btn_del:setTitleColor({r = 65, g = 65, b = 70})
btn_del:setScale9Enabled(true)
btn_del:setCapInsets({x = 15, y = 11, width = 10, height = 18})
btn_del:setLayoutComponentEnabled(true)
btn_del:setName("btn_del")
btn_del:setTag(332)
btn_del:setCascadeColorEnabled(true)
btn_del:setCascadeOpacityEnabled(true)
btn_del:setPosition(544.1815, 43.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_del)
layout:setPositionPercentX(0.9415)
layout:setPositionPercentY(0.5118)
layout:setPercentWidth(0.0692)
layout:setPercentHeight(0.4706)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(524.1815)
layout:setRightMargin(13.8185)
layout:setTopMargin(21.5000)
layout:setBottomMargin(23.5000)
panel_bg:addChild(btn_del)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

