--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("common/bg_box_s.png",0)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 33, y = 33, width = 34, height = 34})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(2)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 800.0000, height = 490.0000})
layout:setLeftMargin(-400.0000)
layout:setRightMargin(-400.0000)
layout:setTopMargin(-245.0000)
layout:setBottomMargin(-245.0000)
Node:addChild(img_bg)

--Create img_line
local img_line = ccui.ImageView:create()
img_line:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_line:loadTexture("hall/common/line.png",1)
img_line:setLayoutComponentEnabled(true)
img_line:setName("img_line")
img_line:setTag(32)
img_line:setCascadeColorEnabled(true)
img_line:setCascadeOpacityEnabled(true)
img_line:setPosition(400.0000, 412.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_line)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8408)
layout:setPercentWidth(0.9837)
layout:setPercentHeight(0.0041)
layout:setSize({width = 787.0000, height = 2.0000})
layout:setLeftMargin(6.5000)
layout:setRightMargin(6.5000)
layout:setTopMargin(77.0000)
layout:setBottomMargin(411.0000)
img_bg:addChild(img_line)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontSize(38)
txt_title:setString([[您有新的更新了]])
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(5)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setPosition(-0.0001, 200.0000)
txt_title:setTextColor({r = 112, g = 41, b = 9})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setSize({width = 267.0000, height = 44.0000})
layout:setLeftMargin(-133.5001)
layout:setRightMargin(-133.4999)
layout:setTopMargin(-222.0000)
layout:setBottomMargin(178.0000)
Node:addChild(txt_title)

--Create sv_content
local sv_content = ccui.ScrollView:create()
sv_content:setInnerContainerSize({width = 702, height = 230})
sv_content:ignoreContentAdaptWithSize(false)
sv_content:setClippingEnabled(true)
sv_content:setBackGroundColorOpacity(102)
sv_content:setLayoutComponentEnabled(true)
sv_content:setName("sv_content")
sv_content:setTag(6)
sv_content:setCascadeColorEnabled(true)
sv_content:setCascadeOpacityEnabled(true)
sv_content:setAnchorPoint(0.5000, 0.5000)
sv_content:setPosition(0.0003, 20.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sv_content)
layout:setSize({width = 680.0000, height = 230.0000})
layout:setLeftMargin(-339.9997)
layout:setRightMargin(-340.0003)
layout:setTopMargin(-135.0000)
layout:setBottomMargin(-95.0000)
Node:addChild(sv_content)

--Create btn_update
local btn_update = ccui.Button:create()
btn_update:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_update:loadTextureNormal("hall/common/btn_green.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_update:loadTexturePressed("hall/common/btn_green.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_update:loadTextureDisabled("hall/common/btn_grey.png",1)
btn_update:setTitleFontSize(14)
btn_update:setTitleColor({r = 65, g = 65, b = 70})
btn_update:setScale9Enabled(true)
btn_update:setCapInsets({x = 9, y = 9, width = 1, height = 1})
btn_update:setLayoutComponentEnabled(true)
btn_update:setName("btn_update")
btn_update:setTag(3)
btn_update:setCascadeColorEnabled(true)
btn_update:setCascadeOpacityEnabled(true)
btn_update:setPosition(160.0000, -167.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_update)
layout:setSize({width = 242.0000, height = 76.0000})
layout:setLeftMargin(39.0000)
layout:setRightMargin(-281.0000)
layout:setTopMargin(129.0001)
layout:setBottomMargin(-205.0001)
Node:addChild(btn_update)

--Create txt_btn_title
local txt_btn_title = ccui.Text:create()
txt_btn_title:ignoreContentAdaptWithSize(true)
txt_btn_title:setTextAreaSize({width = 0, height = 0})
txt_btn_title:setFontSize(36)
txt_btn_title:setString([[更 新]])
txt_btn_title:setLayoutComponentEnabled(true)
txt_btn_title:setName("txt_btn_title")
txt_btn_title:setTag(4)
txt_btn_title:setCascadeColorEnabled(true)
txt_btn_title:setCascadeOpacityEnabled(true)
txt_btn_title:setPosition(121.0000, 36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_btn_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4737)
layout:setPercentWidth(0.3471)
layout:setPercentHeight(0.5395)
layout:setSize({width = 84.0000, height = 41.0000})
layout:setLeftMargin(79.0000)
layout:setRightMargin(79.0000)
layout:setTopMargin(19.5000)
layout:setBottomMargin(15.5000)
btn_update:addChild(txt_btn_title)

--Create btn_exit
local btn_exit = ccui.Button:create()
btn_exit:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_exit:loadTextureNormal("hall/common/btn_blue.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_exit:loadTexturePressed("hall/common/btn_blue.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
btn_exit:loadTextureDisabled("hall/common/btn_grey.png",1)
btn_exit:setTitleFontSize(14)
btn_exit:setTitleColor({r = 65, g = 65, b = 70})
btn_exit:setScale9Enabled(true)
btn_exit:setCapInsets({x = 9, y = 9, width = 1, height = 1})
btn_exit:setLayoutComponentEnabled(true)
btn_exit:setName("btn_exit")
btn_exit:setTag(45)
btn_exit:setCascadeColorEnabled(true)
btn_exit:setCascadeOpacityEnabled(true)
btn_exit:setPosition(-160.0000, -167.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_exit)
layout:setSize({width = 242.0000, height = 76.0000})
layout:setLeftMargin(-281.0000)
layout:setRightMargin(39.0000)
layout:setTopMargin(129.0001)
layout:setBottomMargin(-205.0001)
Node:addChild(btn_exit)

--Create txt_btn_title
local txt_btn_title = ccui.Text:create()
txt_btn_title:ignoreContentAdaptWithSize(true)
txt_btn_title:setTextAreaSize({width = 0, height = 0})
txt_btn_title:setFontSize(36)
txt_btn_title:setString([[退 出]])
txt_btn_title:setLayoutComponentEnabled(true)
txt_btn_title:setName("txt_btn_title")
txt_btn_title:setTag(47)
txt_btn_title:setCascadeColorEnabled(true)
txt_btn_title:setCascadeOpacityEnabled(true)
txt_btn_title:setPosition(121.0000, 36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_btn_title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4737)
layout:setPercentWidth(0.3430)
layout:setPercentHeight(0.5395)
layout:setSize({width = 83.0000, height = 41.0000})
layout:setLeftMargin(79.5000)
layout:setRightMargin(79.5000)
layout:setTopMargin(19.5000)
layout:setBottomMargin(15.5000)
btn_exit:addChild(txt_btn_title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

