--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_di
local img_di = ccui.ImageView:create()
img_di:ignoreContentAdaptWithSize(false)
img_di:loadTexture("hall/login/img_di.png",0)
img_di:setScale9Enabled(true)
img_di:setCapInsets({x = 30, y = 19, width = 4, height = 21})
img_di:setLayoutComponentEnabled(true)
img_di:setName("img_di")
img_di:setTag(78)
img_di:setCascadeColorEnabled(true)
img_di:setCascadeOpacityEnabled(true)
img_di:setAnchorPoint(0.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_di)
layout:setSize({width = 475.0000, height = 59.0000})
layout:setLeftMargin(-237.5000)
layout:setRightMargin(-237.5000)
layout:setTopMargin(-59.0000)
Node:addChild(img_di)

--Create btn_agree
local btn_agree = ccui.Layout:create()
btn_agree:ignoreContentAdaptWithSize(false)
btn_agree:setClippingEnabled(false)
btn_agree:setBackGroundColorOpacity(102)
btn_agree:setTouchEnabled(true);
btn_agree:setLayoutComponentEnabled(true)
btn_agree:setName("btn_agree")
btn_agree:setTag(130)
btn_agree:setCascadeColorEnabled(true)
btn_agree:setCascadeOpacityEnabled(true)
btn_agree:setAnchorPoint(0.5000, 0.5000)
btn_agree:setPosition(146.0000, 28.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_agree)
layout:setPositionPercentX(0.3074)
layout:setPositionPercentY(0.4746)
layout:setPercentWidth(0.5368)
layout:setPercentHeight(1.0169)
layout:setSize({width = 255.0000, height = 60.0000})
layout:setLeftMargin(18.5000)
layout:setRightMargin(201.5000)
layout:setTopMargin(1.0000)
layout:setBottomMargin(-2.0000)
img_di:addChild(btn_agree)

--Create cb_agree
local cb_agree = ccui.CheckBox:create()
cb_agree:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
cb_agree:loadTextureBackGround("hall/login/cb_nor.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
cb_agree:loadTextureBackGroundSelected("hall/login/cb_nor.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
cb_agree:loadTextureBackGroundDisabled("hall/login/cb_nor.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
cb_agree:loadTextureFrontCross("hall/login/cb_sel.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
cb_agree:loadTextureFrontCrossDisabled("hall/login/cb_sel.png",1)
cb_agree:setSelected(true)
cb_agree:setTouchEnabled(false);
cb_agree:setLayoutComponentEnabled(true)
cb_agree:setName("cb_agree")
cb_agree:setTag(79)
cb_agree:setCascadeColorEnabled(true)
cb_agree:setCascadeOpacityEnabled(true)
cb_agree:setPosition(40.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cb_agree)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1569)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1255)
layout:setPercentHeight(0.5333)
layout:setSize({width = 32.0000, height = 32.0000})
layout:setLeftMargin(24.0000)
layout:setRightMargin(199.0000)
layout:setTopMargin(14.0000)
layout:setBottomMargin(14.0000)
btn_agree:addChild(cb_agree)

--Create txt_agree
local txt_agree = ccui.Text:create()
txt_agree:ignoreContentAdaptWithSize(true)
txt_agree:setTextAreaSize({width = 0, height = 0})
txt_agree:setFontSize(26)
txt_agree:setString([[您已阅读并同意]])
txt_agree:setLayoutComponentEnabled(true)
txt_agree:setName("txt_agree")
txt_agree:setTag(131)
txt_agree:setCascadeColorEnabled(true)
txt_agree:setCascadeOpacityEnabled(true)
txt_agree:setAnchorPoint(0.0000, 0.5000)
txt_agree:setPosition(65.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_agree)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2549)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7137)
layout:setPercentHeight(0.4333)
layout:setSize({width = 182.0000, height = 26.0000})
layout:setLeftMargin(65.0000)
layout:setRightMargin(8.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
btn_agree:addChild(txt_agree)

--Create btn_prot
local btn_prot = ccui.Layout:create()
btn_prot:ignoreContentAdaptWithSize(false)
btn_prot:setClippingEnabled(false)
btn_prot:setBackGroundColorOpacity(102)
btn_prot:setTouchEnabled(true);
btn_prot:setLayoutComponentEnabled(true)
btn_prot:setName("btn_prot")
btn_prot:setTag(132)
btn_prot:setCascadeColorEnabled(true)
btn_prot:setCascadeOpacityEnabled(true)
btn_prot:setAnchorPoint(0.5000, 0.5000)
btn_prot:setPosition(353.0000, 28.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_prot)
layout:setPositionPercentX(0.7432)
layout:setPositionPercentY(0.4746)
layout:setPercentWidth(0.2863)
layout:setPercentHeight(1.0169)
layout:setSize({width = 136.0000, height = 60.0000})
layout:setLeftMargin(285.0000)
layout:setRightMargin(54.0000)
layout:setTopMargin(1.0000)
layout:setBottomMargin(-2.0000)
img_di:addChild(btn_prot)

--Create txt_prot
local txt_prot = ccui.Text:create()
txt_prot:ignoreContentAdaptWithSize(true)
txt_prot:setTextAreaSize({width = 0, height = 0})
txt_prot:setFontSize(26)
txt_prot:setString([[《用户协议》]])
txt_prot:setLayoutComponentEnabled(true)
txt_prot:setName("txt_prot")
txt_prot:setTag(134)
txt_prot:setCascadeColorEnabled(true)
txt_prot:setCascadeOpacityEnabled(true)
txt_prot:setAnchorPoint(0.0000, 0.5000)
txt_prot:setPosition(-10.0000, 30.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_prot)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(-0.0735)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.1471)
layout:setPercentHeight(0.4333)
layout:setSize({width = 156.0000, height = 26.0000})
layout:setLeftMargin(-10.0000)
layout:setRightMargin(-10.0000)
layout:setTopMargin(17.0000)
layout:setBottomMargin(17.0000)
btn_prot:addChild(txt_prot)

--Create img_line
local img_line = ccui.ImageView:create()
img_line:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/login.plist")
img_line:loadTexture("hall/login/img_line.png",1)
img_line:setScale9Enabled(true)
img_line:setCapInsets({x = 3, y = 0, width = 6, height = 3})
img_line:setLayoutComponentEnabled(true)
img_line:setName("img_line")
img_line:setTag(135)
img_line:setCascadeColorEnabled(true)
img_line:setCascadeOpacityEnabled(true)
img_line:setPosition(68.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_line)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2667)
layout:setPercentWidth(0.9485)
layout:setPercentHeight(0.0500)
layout:setSize({width = 129.0000, height = 3.0000})
layout:setLeftMargin(3.5000)
layout:setRightMargin(3.5000)
layout:setTopMargin(42.5000)
layout:setBottomMargin(14.5000)
btn_prot:addChild(img_line)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

