--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundImageCapInsets({x = -9, y = -9, width = 23, height = 23})
panel:setBackGroundColorOpacity(150)
panel:setBackGroundImageScale9Enabled(true)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(250)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setSize({width = 274.0000, height = 92.0000})
layout:setRightMargin(-274.0000)
layout:setTopMargin(-92.0000)
Node:addChild(panel)

--Create item_bg_sel
local item_bg_sel = ccui.Layout:create()
item_bg_sel:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
item_bg_sel:setBackGroundImage("hall/common/new_pop_select_bg.png",1)
item_bg_sel:setClippingEnabled(false)
item_bg_sel:setBackGroundImageCapInsets({x = 104, y = 30, width = 66, height = 38})
item_bg_sel:setBackGroundImageScale9Enabled(true)
item_bg_sel:setLayoutComponentEnabled(true)
item_bg_sel:setName("item_bg_sel")
item_bg_sel:setTag(71)
item_bg_sel:setCascadeColorEnabled(true)
item_bg_sel:setCascadeOpacityEnabled(true)
item_bg_sel:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(item_bg_sel)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 274.0000, height = 92.0000})
panel:addChild(item_bg_sel)

--Create item_bg
local item_bg = ccui.Layout:create()
item_bg:ignoreContentAdaptWithSize(false)
item_bg:setClippingEnabled(false)
item_bg:setBackGroundImageCapInsets({x = -10, y = -13, width = 20, height = 25})
item_bg:setBackGroundImageScale9Enabled(true)
item_bg:setLayoutComponentEnabled(true)
item_bg:setName("item_bg")
item_bg:setTag(70)
item_bg:setCascadeColorEnabled(true)
item_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(item_bg)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 274.0000, height = 92.0000})
panel:addChild(item_bg)

--Create img_ico
local img_ico = ccui.ImageView:create()
img_ico:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/messageview.plist")
img_ico:loadTexture("hall/announcement/icon_xf_02.png",1)
img_ico:setLayoutComponentEnabled(true)
img_ico:setName("img_ico")
img_ico:setTag(447)
img_ico:setCascadeColorEnabled(true)
img_ico:setCascadeOpacityEnabled(true)
img_ico:setVisible(false)
img_ico:setPosition(41.0000, 46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_ico)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1496)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1861)
layout:setPercentHeight(0.5543)
layout:setSize({width = 51.0000, height = 51.0000})
layout:setLeftMargin(15.5000)
layout:setRightMargin(207.5000)
layout:setTopMargin(20.5000)
layout:setBottomMargin(20.5000)
panel:addChild(img_ico)

--Create txt_title
local txt_title = ccui.Text:create()
txt_title:ignoreContentAdaptWithSize(true)
txt_title:setTextAreaSize({width = 0, height = 0})
txt_title:setFontName("")
txt_title:setFontSize(28)
txt_title:setString([[系统公告]])
txt_title:setTextVerticalAlignment(1)
txt_title:setLayoutComponentEnabled(true)
txt_title:setName("txt_title")
txt_title:setTag(448)
txt_title:setCascadeColorEnabled(true)
txt_title:setCascadeOpacityEnabled(true)
txt_title:setAnchorPoint(0.0000, 0.5000)
txt_title:setPosition(77.0000, 56.0000)
txt_title:setOpacity(232)
txt_title:setTextColor({r = 255, g = 255, b = 240})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_title)
layout:setPositionPercentX(0.2810)
layout:setPositionPercentY(0.6087)
layout:setPercentWidth(0.4088)
layout:setPercentHeight(0.3043)
layout:setSize({width = 112.0000, height = 28.0000})
layout:setLeftMargin(77.0000)
layout:setRightMargin(85.0000)
layout:setTopMargin(22.0000)
layout:setBottomMargin(42.0000)
panel:addChild(txt_title)

--Create txt_time
local txt_time = ccui.Text:create()
txt_time:ignoreContentAdaptWithSize(true)
txt_time:setTextAreaSize({width = 0, height = 0})
txt_time:setFontName("")
txt_time:setFontSize(18)
txt_time:setString([[03-08 00:00]])
txt_time:setTextVerticalAlignment(1)
txt_time:setLayoutComponentEnabled(true)
txt_time:setName("txt_time")
txt_time:setTag(449)
txt_time:setCascadeColorEnabled(true)
txt_time:setCascadeOpacityEnabled(true)
txt_time:setAnchorPoint(0.0000, 0.5000)
txt_time:setPosition(77.0000, 31.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_time)
layout:setPositionPercentX(0.2810)
layout:setPositionPercentY(0.3370)
layout:setPercentWidth(0.3613)
layout:setPercentHeight(0.1957)
layout:setSize({width = 99.0000, height = 18.0000})
layout:setLeftMargin(77.0000)
layout:setRightMargin(98.0000)
layout:setTopMargin(52.0000)
layout:setBottomMargin(22.0000)
panel:addChild(txt_time)

--Create redPoint
local redPoint = ccui.ImageView:create()
redPoint:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
redPoint:loadTexture("hall/common/new_unread_pt.png",1)
redPoint:setLayoutComponentEnabled(true)
redPoint:setName("redPoint")
redPoint:setTag(479)
redPoint:setCascadeColorEnabled(true)
redPoint:setCascadeOpacityEnabled(true)
redPoint:setPosition(261.1220, 69.7176)
layout = ccui.LayoutComponent:bindLayoutComponent(redPoint)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.9530)
layout:setPositionPercentY(0.7578)
layout:setPercentWidth(0.0730)
layout:setPercentHeight(0.2283)
layout:setSize({width = 20.0000, height = 21.0000})
layout:setLeftMargin(251.1220)
layout:setRightMargin(2.8780)
layout:setTopMargin(11.7824)
layout:setBottomMargin(59.2176)
panel:addChild(redPoint)

--Create lw_bg
local lw_bg = ccui.Layout:create()
lw_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/messageview.plist")
lw_bg:setBackGroundImage("hall/announcement/btn_zlw.png",1)
lw_bg:setClippingEnabled(false)
lw_bg:setBackGroundColorOpacity(0)
lw_bg:setLayoutComponentEnabled(true)
lw_bg:setName("lw_bg")
lw_bg:setTag(72)
lw_bg:setCascadeColorEnabled(true)
lw_bg:setCascadeOpacityEnabled(true)
lw_bg:setAnchorPoint(0.5000, 0.5000)
lw_bg:setPosition(240.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lw_bg)
layout:setPositionPercentX(0.8759)
layout:setPositionPercentY(0.5326)
layout:setPercentWidth(0.1460)
layout:setPercentHeight(0.3913)
layout:setSize({width = 40.0000, height = 36.0000})
layout:setLeftMargin(220.0000)
layout:setRightMargin(14.0000)
layout:setTopMargin(25.0000)
layout:setBottomMargin(31.0000)
panel:addChild(lw_bg)

--Create Img_gg
local Img_gg = ccui.Layout:create()
Img_gg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/messageview.plist")
Img_gg:setBackGroundImage("hall/announcement/icon_xf_01.png",1)
Img_gg:setClippingEnabled(false)
Img_gg:setLayoutComponentEnabled(true)
Img_gg:setName("Img_gg")
Img_gg:setTag(80)
Img_gg:setCascadeColorEnabled(true)
Img_gg:setCascadeOpacityEnabled(true)
Img_gg:setAnchorPoint(0.5000, 0.5000)
Img_gg:setPosition(41.0000, 45.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_gg)
layout:setPositionPercentX(0.1496)
layout:setPositionPercentY(0.4891)
layout:setPercentWidth(0.1861)
layout:setPercentHeight(0.5217)
layout:setSize({width = 51.0000, height = 48.0000})
layout:setLeftMargin(15.5000)
layout:setRightMargin(207.5000)
layout:setTopMargin(23.0000)
layout:setBottomMargin(21.0000)
panel:addChild(Img_gg)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
Image_3:loadTexture("hall/common/new_virtual_line.png",1)
Image_3:setScale9Enabled(true)
Image_3:setCapInsets({x = 15, y = 1, width = 242, height = 1})
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(243)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setAnchorPoint(0.0000, 0.0000)
Image_3:setPosition(0.0000, -0.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentY(-0.0109)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0109)
layout:setSize({width = 274.0000, height = 1.0000})
layout:setTopMargin(91.9999)
layout:setBottomMargin(-0.9999)
panel:addChild(Image_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

