--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_bg
local img_bg = ccui.Layout:create()
img_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
img_bg:setBackGroundImage("hall/room/jxroom/join_bg_1.png",1)
img_bg:setClippingEnabled(false)
img_bg:setBackGroundImageCapInsets({x = 17, y = 17, width = 18, height = 18})
img_bg:setBackGroundColorOpacity(102)
img_bg:setBackGroundImageScale9Enabled(true)
img_bg:setTouchEnabled(true);
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(254)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 1083.0000, height = 662.0000})
layout:setLeftMargin(-541.5000)
layout:setRightMargin(-541.5000)
layout:setTopMargin(-331.0000)
layout:setBottomMargin(-331.0000)
Node:addChild(img_bg)

--Create img_ditu
local img_ditu = ccui.ImageView:create()
img_ditu:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
img_ditu:loadTexture("hall/room/jxroom/create_bg.png",1)
img_ditu:setScale9Enabled(true)
img_ditu:setCapInsets({x = 3, y = 3, width = 4, height = 4})
img_ditu:setLayoutComponentEnabled(true)
img_ditu:setName("img_ditu")
img_ditu:setTag(42)
img_ditu:setCascadeColorEnabled(true)
img_ditu:setCascadeOpacityEnabled(true)
img_ditu:setAnchorPoint(0.0000, 0.0000)
img_ditu:setPosition(12.5000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_ditu)
layout:setPositionPercentX(0.0115)
layout:setPositionPercentY(0.0242)
layout:setPercentWidth(0.9769)
layout:setPercentHeight(0.9577)
layout:setSize({width = 1058.0000, height = 634.0000})
layout:setLeftMargin(12.5000)
layout:setRightMargin(12.5000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(16.0000)
img_bg:addChild(img_ditu)

--Create lv_tab
local lv_tab = ccui.ListView:create()
lv_tab:setDirection(1)
lv_tab:setGravity(0)
lv_tab:ignoreContentAdaptWithSize(false)
lv_tab:setClippingEnabled(true)
lv_tab:setBackGroundImageCapInsets({x = -3, y = -3, width = 6, height = 6})
lv_tab:setBackGroundColorType(1)
lv_tab:setBackGroundColor({r = 255, g = 239, b = 195})
lv_tab:setBackGroundImageScale9Enabled(true)
lv_tab:setLayoutComponentEnabled(true)
lv_tab:setName("lv_tab")
lv_tab:setTag(336)
lv_tab:setCascadeColorEnabled(true)
lv_tab:setCascadeOpacityEnabled(true)
lv_tab:setPosition(12.5000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(lv_tab)
layout:setPositionPercentX(0.0115)
layout:setPositionPercentY(0.0242)
layout:setPercentWidth(0.2050)
layout:setPercentHeight(0.9577)
layout:setSize({width = 222.0000, height = 634.0000})
layout:setLeftMargin(12.5000)
layout:setRightMargin(848.5000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(16.0000)
img_bg:addChild(lv_tab)

--Create nd_subview
local nd_subview=cc.Node:create()
nd_subview:setName("nd_subview")
nd_subview:setTag(201)
nd_subview:setCascadeColorEnabled(true)
nd_subview:setCascadeOpacityEnabled(true)
nd_subview:setPosition(234.5000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nd_subview)
layout:setPositionPercentX(0.2165)
layout:setPositionPercentY(0.0242)
layout:setLeftMargin(234.5000)
layout:setRightMargin(848.5000)
layout:setTopMargin(646.0000)
layout:setBottomMargin(16.0000)
img_bg:addChild(nd_subview)

--Create btn_close
local btn_close = ccui.Layout:create()
btn_close:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
btn_close:setBackGroundImage("hall/room/jxroom/create_close.png",1)
btn_close:setClippingEnabled(false)
btn_close:setBackGroundColorOpacity(102)
btn_close:setTouchEnabled(true);
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(134)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setAnchorPoint(0.5000, 0.5000)
btn_close:setPosition(1042.0000, 623.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.9621)
layout:setPositionPercentY(0.9411)
layout:setPercentWidth(0.0739)
layout:setPercentHeight(0.1208)
layout:setSize({width = 80.0000, height = 80.0000})
layout:setLeftMargin(1002.0000)
layout:setRightMargin(1.0000)
layout:setTopMargin(-1.0000)
layout:setBottomMargin(583.0000)
img_bg:addChild(btn_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

