--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create tab_btn
local tab_btn = ccui.Layout:create()
tab_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
tab_btn:setBackGroundImage("hall/room/jxroom/create_tab_1.png",1)
tab_btn:setClippingEnabled(false)
tab_btn:setBackGroundImageCapInsets({x = 73, y = 37, width = 76, height = 24})
tab_btn:setBackGroundColorOpacity(102)
tab_btn:setBackGroundImageScale9Enabled(true)
tab_btn:setTouchEnabled(true);
tab_btn:setLayoutComponentEnabled(true)
tab_btn:setName("tab_btn")
tab_btn:setTag(56)
tab_btn:setCascadeColorEnabled(true)
tab_btn:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(tab_btn)
layout:setSize({width = 222.0000, height = 90.0000})
layout:setRightMargin(-222.0000)
layout:setTopMargin(-90.0000)
Node:addChild(tab_btn)

--Create img_sel
local img_sel = ccui.ImageView:create()
img_sel:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/jx_room.plist")
img_sel:loadTexture("hall/room/jxroom/create_tab_2.png",1)
img_sel:setScale9Enabled(true)
img_sel:setCapInsets({x = 104, y = 30, width = 14, height = 30})
img_sel:setLayoutComponentEnabled(true)
img_sel:setName("img_sel")
img_sel:setTag(58)
img_sel:setCascadeColorEnabled(true)
img_sel:setCascadeOpacityEnabled(true)
img_sel:setVisible(false)
img_sel:setAnchorPoint(0.5000, 1.0000)
img_sel:setPosition(111.0000, 90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_sel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 222.0000, height = 90.0000})
tab_btn:addChild(img_sel)

--Create txt_game
local txt_game = ccui.Text:create()
txt_game:ignoreContentAdaptWithSize(true)
txt_game:setTextAreaSize({width = 0, height = 0})
txt_game:setFontName("")
txt_game:setFontSize(30)
txt_game:setString([[长春麻将]])
txt_game:setLayoutComponentEnabled(true)
txt_game:setName("txt_game")
txt_game:setTag(60)
txt_game:setCascadeColorEnabled(true)
txt_game:setCascadeOpacityEnabled(true)
txt_game:setPosition(111.0000, 45.0000)
txt_game:setTextColor({r = 136, g = 91, b = 23})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_game)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5405)
layout:setPercentHeight(0.3333)
layout:setSize({width = 120.0000, height = 30.0000})
layout:setLeftMargin(51.0000)
layout:setRightMargin(51.0000)
layout:setTopMargin(30.0000)
layout:setBottomMargin(30.0000)
tab_btn:addChild(txt_game)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

