--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create nd_bottom
innerCSD = require("ui.newhall.hall_bottom_menu")
innerProject = innerCSD.create(callBackProvider)
local nd_bottom = innerProject.root
nd_bottom.animation = innerProject.animation
nd_bottom:setName("nd_bottom")
nd_bottom:setTag(280)
nd_bottom:setCascadeColorEnabled(true)
nd_bottom:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(nd_bottom)
layout:setRightMargin(1280.0000)
layout:setTopMargin(720.0000)
innerProject.animation:setTimeSpeed(1.0000)
nd_bottom:runAction(innerProject.animation)
Layer:addChild(nd_bottom)

--Create nd_top
innerCSD = require("ui.newhall.hall_top_menu")
innerProject = innerCSD.create(callBackProvider)
local nd_top = innerProject.root
nd_top.animation = innerProject.animation
nd_top:setName("nd_top")
nd_top:setTag(150)
nd_top:setCascadeColorEnabled(true)
nd_top:setCascadeOpacityEnabled(true)
nd_top:setPosition(1280.0000, 671.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nd_top)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(1.0000)
layout:setPositionPercentY(0.9319)
layout:setLeftMargin(1280.0000)
layout:setTopMargin(49.0000)
layout:setBottomMargin(671.0000)
innerProject.animation:setTimeSpeed(1.0000)
nd_top:runAction(innerProject.animation)
Layer:addChild(nd_top)

--Create nd_userinfo
innerCSD = require("ui.newhall.hall_userinfo")
innerProject = innerCSD.create(callBackProvider)
local nd_userinfo = innerProject.root
nd_userinfo.animation = innerProject.animation
nd_userinfo:setName("nd_userinfo")
nd_userinfo:setTag(242)
nd_userinfo:setCascadeColorEnabled(true)
nd_userinfo:setCascadeOpacityEnabled(true)
nd_userinfo:setPosition(0.0000, 666.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nd_userinfo)
layout:setPositionPercentY(0.9250)
layout:setRightMargin(1280.0000)
layout:setTopMargin(54.0000)
layout:setBottomMargin(666.0000)
innerProject.animation:setTimeSpeed(1.0000)
nd_userinfo:runAction(innerProject.animation)
Layer:addChild(nd_userinfo)

--Create nd_left
local nd_left=cc.Node:create()
nd_left:setName("nd_left")
nd_left:setTag(89)
nd_left:setCascadeColorEnabled(true)
nd_left:setCascadeOpacityEnabled(true)
nd_left:setPosition(0.0000, 545.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nd_left)
layout:setPositionPercentY(0.7569)
layout:setRightMargin(1280.0000)
layout:setTopMargin(175.0000)
layout:setBottomMargin(545.0000)
Layer:addChild(nd_left)

--Create btn_arena
local btn_arena = ccui.Button:create()
btn_arena:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/newhall.plist")
btn_arena:loadTextureNormal("hall/newhall/btn_arena.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/newhall.plist")
btn_arena:loadTexturePressed("hall/newhall/btn_arena.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/newhall.plist")
btn_arena:loadTextureDisabled("hall/newhall/btn_arena.png",1)
btn_arena:setTitleFontSize(14)
btn_arena:setTitleColor({r = 65, g = 65, b = 70})
btn_arena:setScale9Enabled(true)
btn_arena:setCapInsets({x = 15, y = 11, width = 158, height = 120})
btn_arena:setLayoutComponentEnabled(true)
btn_arena:setName("btn_arena")
btn_arena:setTag(643)
btn_arena:setCascadeColorEnabled(true)
btn_arena:setCascadeOpacityEnabled(true)
btn_arena:setPosition(113.0000, -46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_arena)
layout:setSize({width = 188.0000, height = 142.0000})
layout:setLeftMargin(19.0000)
layout:setRightMargin(-207.0000)
layout:setTopMargin(-25.0000)
layout:setBottomMargin(-117.0000)
nd_left:addChild(btn_arena)

--Create btn_month_card
local btn_month_card = ccui.Button:create()
btn_month_card:ignoreContentAdaptWithSize(false)
btn_month_card:loadTextureNormal("hall/newhall/btn_zgyk.png",0)
btn_month_card:loadTexturePressed("hall/newhall/btn_zgyk.png",0)
btn_month_card:loadTextureDisabled("hall/newhall/btn_zgyk.png",0)
btn_month_card:setTitleFontSize(14)
btn_month_card:setTitleColor({r = 65, g = 65, b = 70})
btn_month_card:setScale9Enabled(true)
btn_month_card:setCapInsets({x = 15, y = 11, width = 158, height = 114})
btn_month_card:setLayoutComponentEnabled(true)
btn_month_card:setName("btn_month_card")
btn_month_card:setTag(554)
btn_month_card:setCascadeColorEnabled(true)
btn_month_card:setCascadeOpacityEnabled(true)
btn_month_card:setPosition(113.0000, -191.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_month_card)
layout:setSize({width = 188.0000, height = 136.0000})
layout:setLeftMargin(19.0000)
layout:setRightMargin(-207.0000)
layout:setTopMargin(123.0000)
layout:setBottomMargin(-259.0000)
nd_left:addChild(btn_month_card)

--Create ani_card
innerCSD = require("ui.newhall.hall_month_card_btn")
innerProject = innerCSD.create(callBackProvider)
local ani_card = innerProject.root
ani_card.animation = innerProject.animation
ani_card:setName("ani_card")
ani_card:setTag(190)
ani_card:setCascadeColorEnabled(true)
ani_card:setCascadeOpacityEnabled(true)
ani_card:setPosition(94.0000, 75.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ani_card)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5515)
layout:setLeftMargin(94.0000)
layout:setRightMargin(94.0000)
layout:setTopMargin(61.0000)
layout:setBottomMargin(75.0000)
innerProject.animation:setTimeSpeed(1.0000)
ani_card:runAction(innerProject.animation)
btn_month_card:addChild(ani_card)

--Create img_ljlq
local img_ljlq = ccui.ImageView:create()
img_ljlq:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/newhall.plist")
img_ljlq:loadTexture("hall/newhall/txt_ljlq.png",1)
img_ljlq:setLayoutComponentEnabled(true)
img_ljlq:setName("img_ljlq")
img_ljlq:setTag(556)
img_ljlq:setCascadeColorEnabled(true)
img_ljlq:setCascadeOpacityEnabled(true)
img_ljlq:setVisible(false)
img_ljlq:setPosition(129.0000, 15.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_ljlq)
layout:setPositionPercentX(0.6862)
layout:setPositionPercentY(0.1103)
layout:setPercentWidth(0.5106)
layout:setPercentHeight(0.1691)
layout:setSize({width = 96.0000, height = 23.0000})
layout:setLeftMargin(81.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(109.5000)
layout:setBottomMargin(3.5000)
btn_month_card:addChild(img_ljlq)

--Create img_zgyk
local img_zgyk = ccui.ImageView:create()
img_zgyk:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/newhall.plist")
img_zgyk:loadTexture("hall/newhall/txt_zgyk.png",1)
img_zgyk:setLayoutComponentEnabled(true)
img_zgyk:setName("img_zgyk")
img_zgyk:setTag(555)
img_zgyk:setCascadeColorEnabled(true)
img_zgyk:setCascadeOpacityEnabled(true)
img_zgyk:setPosition(129.0000, 15.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_zgyk)
layout:setPositionPercentX(0.6862)
layout:setPositionPercentY(0.1103)
layout:setPercentWidth(0.5106)
layout:setPercentHeight(0.1691)
layout:setSize({width = 96.0000, height = 23.0000})
layout:setLeftMargin(81.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(109.5000)
layout:setBottomMargin(3.5000)
btn_month_card:addChild(img_zgyk)

--Create btn_share
local btn_share = ccui.Button:create()
btn_share:ignoreContentAdaptWithSize(false)
btn_share:loadTextureNormal("hall/newhall/btn_zgyk.png",0)
btn_share:loadTexturePressed("hall/newhall/btn_zgyk.png",0)
btn_share:loadTextureDisabled("hall/newhall/btn_zgyk.png",0)
btn_share:setTitleFontSize(14)
btn_share:setTitleColor({r = 65, g = 65, b = 70})
btn_share:setScale9Enabled(true)
btn_share:setCapInsets({x = 15, y = 11, width = 158, height = 114})
btn_share:setLayoutComponentEnabled(true)
btn_share:setName("btn_share")
btn_share:setTag(378)
btn_share:setCascadeColorEnabled(true)
btn_share:setCascadeOpacityEnabled(true)
btn_share:setPosition(113.0000, -336.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_share)
layout:setSize({width = 188.0000, height = 136.0000})
layout:setLeftMargin(19.0000)
layout:setRightMargin(-207.0000)
layout:setTopMargin(268.0000)
layout:setBottomMargin(-404.0000)
nd_left:addChild(btn_share)

--Create ani_share
innerCSD = require("ui.newhall.hall_share_btn")
innerProject = innerCSD.create(callBackProvider)
local ani_share = innerProject.root
ani_share.animation = innerProject.animation
ani_share:setName("ani_share")
ani_share:setTag(379)
ani_share:setCascadeColorEnabled(true)
ani_share:setCascadeOpacityEnabled(true)
ani_share:setPosition(94.0000, 75.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ani_share)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5515)
layout:setLeftMargin(94.0000)
layout:setRightMargin(94.0000)
layout:setTopMargin(61.0000)
layout:setBottomMargin(75.0000)
innerProject.animation:setTimeSpeed(1.0000)
ani_share:runAction(innerProject.animation)
btn_share:addChild(ani_share)

--Create img_fxyl
local img_fxyl = ccui.ImageView:create()
img_fxyl:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/newhall.plist")
img_fxyl:loadTexture("hall/newhall/txt_fxyl.png",1)
img_fxyl:setLayoutComponentEnabled(true)
img_fxyl:setName("img_fxyl")
img_fxyl:setTag(387)
img_fxyl:setCascadeColorEnabled(true)
img_fxyl:setCascadeOpacityEnabled(true)
img_fxyl:setPosition(129.0000, 15.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_fxyl)
layout:setPositionPercentX(0.6862)
layout:setPositionPercentY(0.1103)
layout:setPercentWidth(0.5106)
layout:setPercentHeight(0.1691)
layout:setSize({width = 96.0000, height = 23.0000})
layout:setLeftMargin(81.0000)
layout:setRightMargin(11.0000)
layout:setTopMargin(109.5000)
layout:setBottomMargin(3.5000)
btn_share:addChild(img_fxyl)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

