--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create pnl_content
local pnl_content = ccui.Layout:create()
pnl_content:ignoreContentAdaptWithSize(false)
pnl_content:setClippingEnabled(false)
pnl_content:setTouchEnabled(true);
pnl_content:setLayoutComponentEnabled(true)
pnl_content:setName("pnl_content")
pnl_content:setTag(73)
pnl_content:setCascadeColorEnabled(true)
pnl_content:setCascadeOpacityEnabled(true)
pnl_content:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(pnl_content)
layout:setSize({width = 448.0000, height = 434.0000})
layout:setLeftMargin(-224.0000)
layout:setRightMargin(-224.0000)
layout:setTopMargin(-217.0000)
layout:setBottomMargin(-217.0000)
Node:addChild(pnl_content)

--Create img_projection
local img_projection = ccui.ImageView:create()
img_projection:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/vip_detailed.plist")
img_projection:loadTexture("hall/vip_detailed/vip_desc_projection .png",1)
img_projection:setScale9Enabled(true)
img_projection:setCapInsets({x = 35, y = 37, width = 28, height = 23})
img_projection:setLayoutComponentEnabled(true)
img_projection:setName("img_projection")
img_projection:setTag(69)
img_projection:setCascadeColorEnabled(true)
img_projection:setCascadeOpacityEnabled(true)
img_projection:setPosition(224.9997, 215.9989)
layout = ccui.LayoutComponent:bindLayoutComponent(img_projection)
layout:setPositionPercentX(0.5022)
layout:setPositionPercentY(0.4977)
layout:setPercentWidth(1.0045)
layout:setPercentHeight(1.0000)
layout:setSize({width = 450.0000, height = 434.0000})
layout:setLeftMargin(-0.0003)
layout:setRightMargin(-1.9997)
layout:setTopMargin(1.0011)
layout:setBottomMargin(-1.0011)
pnl_content:addChild(img_projection)

--Create img_mid
local img_mid = ccui.ImageView:create()
img_mid:ignoreContentAdaptWithSize(false)
img_mid:loadTexture("hall/vip_detailed/vip1_desc_mid.png",0)
img_mid:setScale9Enabled(true)
img_mid:setCapInsets({x = 15, y = 16, width = 382, height = 291})
img_mid:setLayoutComponentEnabled(true)
img_mid:setName("img_mid")
img_mid:setTag(72)
img_mid:setCascadeColorEnabled(true)
img_mid:setCascadeOpacityEnabled(true)
img_mid:setPosition(224.0000, 194.6987)
layout = ccui.LayoutComponent:bindLayoutComponent(img_mid)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4486)
layout:setPercentWidth(0.9286)
layout:setPercentHeight(0.7442)
layout:setSize({width = 416.0000, height = 323.0000})
layout:setLeftMargin(16.0000)
layout:setRightMargin(16.0000)
layout:setTopMargin(77.8013)
layout:setBottomMargin(33.1987)
pnl_content:addChild(img_mid)

--Create img_top
local img_top = ccui.ImageView:create()
img_top:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/vip_detailed.plist")
img_top:loadTexture("hall/vip_detailed/vip_desc_top.png",1)
img_top:setScale9Enabled(true)
img_top:setCapInsets({x = 18, y = 21, width = 11, height = 13})
img_top:setLayoutComponentEnabled(true)
img_top:setName("img_top")
img_top:setTag(73)
img_top:setCascadeColorEnabled(true)
img_top:setCascadeOpacityEnabled(true)
img_top:setAnchorPoint(0.0000, 0.0000)
img_top:setPosition(0.0000, 323.0000)
img_top:setColor({r = 21, g = 184, b = 155})
layout = ccui.LayoutComponent:bindLayoutComponent(img_top)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1920)
layout:setSize({width = 416.0000, height = 62.0000})
layout:setTopMargin(-62.0000)
layout:setBottomMargin(323.0000)
img_mid:addChild(img_top)

--Create img_lowner
local img_lowner = ccui.ImageView:create()
img_lowner:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/vip_detailed.plist")
img_lowner:loadTexture("hall/vip_detailed/vip_desc_lower.png",1)
img_lowner:setScale9Enabled(true)
img_lowner:setCapInsets({x = 19, y = 5, width = 8, height = 6})
img_lowner:setLayoutComponentEnabled(true)
img_lowner:setName("img_lowner")
img_lowner:setTag(74)
img_lowner:setCascadeColorEnabled(true)
img_lowner:setCascadeOpacityEnabled(true)
img_lowner:setAnchorPoint(0.0000, 1.0000)
img_lowner:setColor({r = 21, g = 184, b = 155})
layout = ccui.LayoutComponent:bindLayoutComponent(img_lowner)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.0495)
layout:setSize({width = 416.0000, height = 16.0000})
layout:setTopMargin(323.0000)
layout:setBottomMargin(-16.0000)
img_mid:addChild(img_lowner)

--Create img_2
local img_2 = ccui.ImageView:create()
img_2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/vip_detailed.plist")
img_2:loadTexture("hall/vip_detailed/vip_desc_pattern.png",1)
img_2:setLayoutComponentEnabled(true)
img_2:setName("img_2")
img_2:setTag(68)
img_2:setCascadeColorEnabled(true)
img_2:setCascadeOpacityEnabled(true)
img_2:setPosition(276.0001, 352.9998)
layout = ccui.LayoutComponent:bindLayoutComponent(img_2)
layout:setPositionPercentX(0.6635)
layout:setPositionPercentY(1.0929)
layout:setPercentWidth(0.6731)
layout:setPercentHeight(0.1920)
layout:setSize({width = 280.0000, height = 62.0000})
layout:setLeftMargin(136.0001)
layout:setRightMargin(-0.0001)
layout:setTopMargin(-60.9998)
layout:setBottomMargin(321.9998)
img_mid:addChild(img_2)

--Create img_privilege
local img_privilege = ccui.ImageView:create()
img_privilege:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/vip_detailed.plist")
img_privilege:loadTexture("hall/vip_detailed/vip_privilege .png",1)
img_privilege:setLayoutComponentEnabled(true)
img_privilege:setName("img_privilege")
img_privilege:setTag(71)
img_privilege:setCascadeColorEnabled(true)
img_privilege:setCascadeOpacityEnabled(true)
img_privilege:setPosition(226.9998, 352.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_privilege)
layout:setPositionPercentX(0.5457)
layout:setPositionPercentY(1.0898)
layout:setPercentWidth(0.1346)
layout:setPercentHeight(0.0867)
layout:setSize({width = 56.0000, height = 28.0000})
layout:setLeftMargin(198.9998)
layout:setRightMargin(161.0002)
layout:setTopMargin(-43.0000)
layout:setBottomMargin(338.0000)
img_mid:addChild(img_privilege)

--Create atlas_vip_num
local atlas_vip_num = ccui.TextAtlas:create([[5]],
													"hall/vip_detailed/vip_words_w.png",
													20,
													26,
													"0")
atlas_vip_num:setLayoutComponentEnabled(true)
atlas_vip_num:setName("atlas_vip_num")
atlas_vip_num:setTag(192)
atlas_vip_num:setCascadeColorEnabled(true)
atlas_vip_num:setCascadeOpacityEnabled(true)
atlas_vip_num:setAnchorPoint(0.0000, 0.5000)
atlas_vip_num:setPosition(154.9998, 352.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(atlas_vip_num)
layout:setPositionPercentX(0.3726)
layout:setPositionPercentY(1.0898)
layout:setPercentWidth(0.0481)
layout:setPercentHeight(0.0805)
layout:setSize({width = 20.0000, height = 26.0000})
layout:setLeftMargin(154.9998)
layout:setRightMargin(241.0002)
layout:setTopMargin(-42.0001)
layout:setBottomMargin(339.0001)
img_mid:addChild(atlas_vip_num)

--Create img_vip
local img_vip = ccui.ImageView:create()
img_vip:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/vip_detailed.plist")
img_vip:loadTexture("hall/vip_detailed/vip_words_v_w.png",1)
img_vip:setLayoutComponentEnabled(true)
img_vip:setName("img_vip")
img_vip:setTag(193)
img_vip:setCascadeColorEnabled(true)
img_vip:setCascadeOpacityEnabled(true)
img_vip:setAnchorPoint(1.0000, 0.5000)
img_vip:setPosition(154.9998, 351.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_vip)
layout:setPositionPercentX(0.3726)
layout:setPositionPercentY(1.0867)
layout:setPercentWidth(0.1779)
layout:setPercentHeight(0.0805)
layout:setSize({width = 74.0000, height = 26.0000})
layout:setLeftMargin(80.9998)
layout:setRightMargin(261.0002)
layout:setTopMargin(-41.0000)
layout:setBottomMargin(338.0000)
img_mid:addChild(img_vip)

--Create img_vip_icon
local img_vip_icon = ccui.ImageView:create()
img_vip_icon:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/vip_detailed.plist")
img_vip_icon:loadTexture("hall/vip_detailed/vip_desc_icon.png",1)
img_vip_icon:setLayoutComponentEnabled(true)
img_vip_icon:setName("img_vip_icon")
img_vip_icon:setTag(70)
img_vip_icon:setCascadeColorEnabled(true)
img_vip_icon:setCascadeOpacityEnabled(true)
img_vip_icon:setPosition(49.9998, 351.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(img_vip_icon)
layout:setPositionPercentX(0.1202)
layout:setPositionPercentY(1.0867)
layout:setPercentWidth(0.1058)
layout:setPercentHeight(0.1053)
layout:setSize({width = 44.0000, height = 34.0000})
layout:setLeftMargin(27.9998)
layout:setRightMargin(344.0002)
layout:setTopMargin(-45.0002)
layout:setBottomMargin(334.0002)
img_mid:addChild(img_vip_icon)

--Create img_selected
local img_selected = ccui.ImageView:create()
img_selected:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/vip_detailed.plist")
img_selected:loadTexture("hall/vip_detailed/btn_orange.png",1)
img_selected:setScale9Enabled(true)
img_selected:setCapInsets({x = 42, y = 41, width = 1, height = 1})
img_selected:setLayoutComponentEnabled(true)
img_selected:setName("img_selected")
img_selected:setTag(72)
img_selected:setCascadeColorEnabled(true)
img_selected:setCascadeOpacityEnabled(true)
img_selected:setPosition(224.0002, 218.0002)
layout = ccui.LayoutComponent:bindLayoutComponent(img_selected)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5023)
layout:setPercentWidth(1.0045)
layout:setPercentHeight(1.0000)
layout:setSize({width = 450.0000, height = 434.0000})
layout:setLeftMargin(-0.9998)
layout:setRightMargin(-1.0002)
layout:setTopMargin(-1.0002)
layout:setBottomMargin(1.0002)
pnl_content:addChild(img_selected)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

