--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("hall/common.plist")
img_bg:loadTexture("hall/common/bg_bg_1.png",1)
img_bg:setScale9Enabled(true)
img_bg:setCapInsets({x = 44, y = 44, width = 1, height = 1})
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(244)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setSize({width = 890.0000, height = 610.0000})
layout:setLeftMargin(-445.0000)
layout:setRightMargin(-445.0000)
layout:setTopMargin(-305.0000)
layout:setBottomMargin(-305.0000)
Node:addChild(img_bg)

--Create pv_picture
local pv_picture = ccui.PageView:create()
pv_picture:ignoreContentAdaptWithSize(false)
pv_picture:setBackGroundImage("common/pixels_white.png",0)
pv_picture:setClippingEnabled(true)
pv_picture:setBackGroundImageCapInsets({x = 0, y = 0, width = 2, height = 2})
pv_picture:setBackGroundColorOpacity(102)
pv_picture:setBackGroundImageScale9Enabled(true)
pv_picture:setLayoutComponentEnabled(true)
pv_picture:setName("pv_picture")
pv_picture:setTag(176)
pv_picture:setCascadeColorEnabled(true)
pv_picture:setCascadeOpacityEnabled(true)
pv_picture:setAnchorPoint(0.5000, 0.0000)
pv_picture:setPosition(458.8472, 200.9083)
layout = ccui.LayoutComponent:bindLayoutComponent(pv_picture)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5156)
layout:setPositionPercentY(0.3294)
layout:setPercentWidth(0.9213)
layout:setPercentHeight(0.6295)
layout:setSize({width = 820.0000, height = 384.0000})
layout:setLeftMargin(48.8472)
layout:setRightMargin(21.1528)
layout:setTopMargin(25.0917)
layout:setBottomMargin(200.9083)
img_bg:addChild(pv_picture)

--Create btn_close
local btn_close = ccui.Button:create()
btn_close:ignoreContentAdaptWithSize(false)
btn_close:loadTextureNormal("common/btn_close.png",0)
btn_close:loadTexturePressed("common/btn_close.png",0)
btn_close:loadTextureDisabled("common/btn_close.png",0)
btn_close:setTitleFontSize(14)
btn_close:setTitleColor({r = 65, g = 65, b = 70})
btn_close:setScale9Enabled(true)
btn_close:setCapInsets({x = 15, y = 11, width = 40, height = 50})
btn_close:setLayoutComponentEnabled(true)
btn_close:setName("btn_close")
btn_close:setTag(247)
btn_close:setCascadeColorEnabled(true)
btn_close:setCascadeOpacityEnabled(true)
btn_close:setPosition(880.0007, 599.9985)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_close)
layout:setPositionPercentX(0.9888)
layout:setPositionPercentY(0.9836)
layout:setPercentWidth(0.0787)
layout:setPercentHeight(0.1180)
layout:setSize({width = 70.0000, height = 72.0000})
layout:setLeftMargin(845.0007)
layout:setRightMargin(-25.0007)
layout:setTopMargin(-25.9985)
layout:setBottomMargin(563.9985)
img_bg:addChild(btn_close)

--Create img_left_line
local img_left_line = ccui.ImageView:create()
img_left_line:ignoreContentAdaptWithSize(false)
img_left_line:loadTexture("hall/common/pic_top_l.png",0)
img_left_line:setLayoutComponentEnabled(true)
img_left_line:setName("img_left_line")
img_left_line:setTag(297)
img_left_line:setCascadeColorEnabled(true)
img_left_line:setCascadeOpacityEnabled(true)
img_left_line:setAnchorPoint(1.0000, 0.5000)
img_left_line:setPosition(200.0000, 155.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_left_line)
layout:setPositionPercentX(0.2247)
layout:setPositionPercentY(0.2541)
layout:setPercentWidth(0.1775)
layout:setPercentHeight(0.0295)
layout:setSize({width = 158.0000, height = 18.0000})
layout:setLeftMargin(42.0000)
layout:setRightMargin(690.0000)
layout:setTopMargin(446.0000)
layout:setBottomMargin(146.0000)
img_bg:addChild(img_left_line)

--Create img_right_line
local img_right_line = ccui.ImageView:create()
img_right_line:ignoreContentAdaptWithSize(false)
img_right_line:loadTexture("hall/common/pic_top_r.png",0)
img_right_line:setLayoutComponentEnabled(true)
img_right_line:setName("img_right_line")
img_right_line:setTag(298)
img_right_line:setCascadeColorEnabled(true)
img_right_line:setCascadeOpacityEnabled(true)
img_right_line:setAnchorPoint(0.0000, 0.5000)
img_right_line:setPosition(690.0000, 155.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_right_line)
layout:setPositionPercentX(0.7753)
layout:setPositionPercentY(0.2541)
layout:setPercentWidth(0.1775)
layout:setPercentHeight(0.0295)
layout:setSize({width = 158.0000, height = 18.0000})
layout:setLeftMargin(690.0000)
layout:setRightMargin(42.0000)
layout:setTopMargin(446.0000)
layout:setBottomMargin(146.0000)
img_bg:addChild(img_right_line)

--Create txt_tips
local txt_tips = ccui.Text:create()
txt_tips:ignoreContentAdaptWithSize(true)
txt_tips:setTextAreaSize({width = 0, height = 0})
txt_tips:setFontSize(32)
txt_tips:setString([[购买房卡或申请推广员请联系]])
txt_tips:setLayoutComponentEnabled(true)
txt_tips:setName("txt_tips")
txt_tips:setTag(246)
txt_tips:setCascadeColorEnabled(true)
txt_tips:setCascadeOpacityEnabled(true)
txt_tips:setPosition(445.0000, 155.0007)
txt_tips:setTextColor({r = 119, g = 91, b = 66})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_tips)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2541)
layout:setPercentWidth(0.4708)
layout:setPercentHeight(0.0607)
layout:setSize({width = 419.0000, height = 37.0000})
layout:setLeftMargin(235.5000)
layout:setRightMargin(235.5000)
layout:setTopMargin(436.4993)
layout:setBottomMargin(136.5007)
img_bg:addChild(txt_tips)

--Create txt_str_wx
local txt_str_wx = ccui.Text:create()
txt_str_wx:ignoreContentAdaptWithSize(true)
txt_str_wx:setTextAreaSize({width = 0, height = 0})

txt_str_wx:setFontSize(38)
txt_str_wx:setString([[微信号：]])
txt_str_wx:setLayoutComponentEnabled(true)
txt_str_wx:setName("txt_str_wx")
txt_str_wx:setTag(299)
txt_str_wx:setCascadeColorEnabled(true)
txt_str_wx:setCascadeOpacityEnabled(true)
txt_str_wx:setPosition(238.0002, 85.0000)
txt_str_wx:setTextColor({r = 88, g = 144, b = 89})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_str_wx)
layout:setPositionPercentX(0.2674)
layout:setPositionPercentY(0.1393)
layout:setPercentWidth(0.1461)
layout:setPercentHeight(0.0721)
layout:setSize({width = 130.0000, height = 44.0000})
layout:setLeftMargin(173.0002)
layout:setRightMargin(586.9998)
layout:setTopMargin(503.0000)
layout:setBottomMargin(63.0000)
img_bg:addChild(txt_str_wx)

--Create txt_wx
local txt_wx = ccui.Text:create()
txt_wx:ignoreContentAdaptWithSize(true)
txt_wx:setTextAreaSize({width = 0, height = 0})
txt_wx:setFontSize(50)
txt_wx:setString([[abdc123456]])
txt_wx:setLayoutComponentEnabled(true)
txt_wx:setName("txt_wx")
txt_wx:setTag(300)
txt_wx:setCascadeColorEnabled(true)
txt_wx:setCascadeOpacityEnabled(true)
txt_wx:setAnchorPoint(0.0000, 0.5000)
txt_wx:setPosition(321.0005, 85.0000)
txt_wx:setTextColor({r = 2, g = 117, b = 5})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_wx)
layout:setPositionPercentX(0.3607)
layout:setPositionPercentY(0.1393)
layout:setPercentWidth(0.3079)
layout:setPercentHeight(0.0934)
layout:setSize({width = 274.0000, height = 57.0000})
layout:setLeftMargin(321.0005)
layout:setRightMargin(294.9995)
layout:setTopMargin(496.5000)
layout:setBottomMargin(56.5000)
img_bg:addChild(txt_wx)

--Create btn_copy
local btn_copy = ccui.Layout:create()
btn_copy:ignoreContentAdaptWithSize(false)
btn_copy:setClippingEnabled(false)
btn_copy:setBackGroundColorOpacity(102)
btn_copy:setTouchEnabled(true);
btn_copy:setLayoutComponentEnabled(true)
btn_copy:setName("btn_copy")
btn_copy:setTag(301)
btn_copy:setCascadeColorEnabled(true)
btn_copy:setCascadeOpacityEnabled(true)
btn_copy:setAnchorPoint(0.0000, 0.5000)
btn_copy:setPosition(660.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_copy)
layout:setPositionPercentX(0.7416)
layout:setPositionPercentY(0.1393)
layout:setPercentWidth(0.1685)
layout:setPercentHeight(0.1148)
layout:setSize({width = 150.0000, height = 70.0000})
layout:setLeftMargin(660.0000)
layout:setRightMargin(80.0000)
layout:setTopMargin(490.0000)
layout:setBottomMargin(50.0000)
img_bg:addChild(btn_copy)

--Create txt_copy
local txt_copy = ccui.Text:create()
txt_copy:ignoreContentAdaptWithSize(true)
txt_copy:setTextAreaSize({width = 0, height = 0})
txt_copy:setFontSize(40)
txt_copy:setString([[复 制]])
txt_copy:setLayoutComponentEnabled(true)
txt_copy:setName("txt_copy")
txt_copy:setTag(302)
txt_copy:setCascadeColorEnabled(true)
txt_copy:setCascadeOpacityEnabled(true)
txt_copy:setPosition(75.0000, 35.0000)
txt_copy:setTextColor({r = 15, g = 144, b = 212})
layout = ccui.LayoutComponent:bindLayoutComponent(txt_copy)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6133)
layout:setPercentHeight(0.6571)
layout:setSize({width = 92.0000, height = 46.0000})
layout:setLeftMargin(29.0000)
layout:setRightMargin(29.0000)
layout:setTopMargin(12.0000)
layout:setBottomMargin(12.0000)
btn_copy:addChild(txt_copy)

--Create txt_line
local txt_line = ccui.Layout:create()
txt_line:ignoreContentAdaptWithSize(false)
txt_line:setClippingEnabled(false)
txt_line:setBackGroundColorType(1)
txt_line:setBackGroundColor({r = 15, g = 144, b = 212})
txt_line:setTouchEnabled(true);
txt_line:setLayoutComponentEnabled(true)
txt_line:setName("txt_line")
txt_line:setTag(303)
txt_line:setCascadeColorEnabled(true)
txt_line:setCascadeOpacityEnabled(true)
txt_line:setAnchorPoint(0.5000, 0.0000)
txt_line:setPosition(75.0000, 16.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(txt_line)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2286)
layout:setPercentWidth(0.6000)
layout:setPercentHeight(0.0286)
layout:setSize({width = 90.0000, height = 2.0000})
layout:setLeftMargin(30.0000)
layout:setRightMargin(30.0000)
layout:setTopMargin(52.0000)
layout:setBottomMargin(16.0000)
btn_copy:addChild(txt_line)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

